import { ExamDomain } from '@/lib/exams/types'

/**
 * AI-900 functional groups, mirroring the official skills-measured outline
 * (as of May 2, 2025). Weights sum to the published exam blueprint.
 */
export const AI900_DOMAINS: ExamDomain[] = [
  {
    id: 'ai-workloads',
    name: 'Describe AI workloads and considerations',
    weight: '15-20%',
    description: 'Identify common AI workloads and the guiding principles of responsible AI.',
    topics: [
      'Identify computer vision workloads',
      'Identify natural language processing workloads',
      'Identify document processing workloads',
      'Identify features of generative AI workloads',
      'Responsible AI: fairness',
      'Responsible AI: reliability and safety',
      'Responsible AI: privacy and security',
      'Responsible AI: inclusiveness',
      'Responsible AI: transparency',
      'Responsible AI: accountability',
    ],
    examTips: [
      'Match each scenario to ONE workload type: vision, NLP, document processing, or generative AI.',
      'Memorize the 6 responsible AI principles and a one-line example of each.',
      'Fairness = treat all groups equitably; Accountability = humans are responsible/governed.',
      'Reliability & safety = performs reliably under expected and unexpected conditions.',
      'Transparency = users understand how/why a decision was made.',
    ],
    officialDocUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/responsible-use-of-ai-overview',
  },
  {
    id: 'machine-learning',
    name: 'Describe fundamental principles of machine learning on Azure',
    weight: '15-20%',
    description: 'Identify ML techniques, core concepts, and Azure Machine Learning capabilities.',
    topics: [
      'Regression scenarios',
      'Classification scenarios',
      'Clustering scenarios',
      'Deep learning features',
      'The Transformer architecture',
      'Features and labels in a dataset',
      'Training and validation datasets',
      'Automated machine learning (AutoML)',
      'Data and compute services for ML',
      'Model management and deployment in Azure ML',
    ],
    examTips: [
      'Regression → predict a NUMBER; Classification → predict a CATEGORY/label; Clustering → group UNLABELED data.',
      'Features = input columns (X); Label = the value you predict (Y).',
      'Split data into training + validation to measure how the model generalizes.',
      'AutoML tries many algorithms/hyperparameters automatically to find the best model.',
      'Azure ML designer = no-code drag-and-drop pipeline builder.',
    ],
    officialDocUrl: 'https://learn.microsoft.com/en-us/azure/machine-learning/overview-what-is-azure-machine-learning',
  },
  {
    id: 'computer-vision',
    name: 'Describe features of computer vision workloads on Azure',
    weight: '15-20%',
    description: 'Identify computer vision solution types and the Azure services that power them.',
    topics: [
      'Image classification',
      'Object detection',
      'Optical character recognition (OCR)',
      'Facial detection and facial analysis',
      'Azure AI Vision service capabilities',
      'Azure AI Face service capabilities',
    ],
    examTips: [
      'Image classification → ONE label for the whole image; Object detection → labels + bounding boxes for each object.',
      'OCR → extract printed/handwritten text; Read API for documents and images.',
      'Azure AI Face → detection, verification, identification, and facial attributes.',
      'Custom Vision → train your own image classification/object detection models.',
      'A bounding box (coordinates) is the giveaway for object detection.',
    ],
    officialDocUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/computer-vision/overview',
  },
  {
    id: 'nlp',
    name: 'Describe features of NLP workloads on Azure',
    weight: '15-20%',
    description: 'Identify NLP scenarios and the Azure AI Language and Speech services.',
    topics: [
      'Key phrase extraction',
      'Entity recognition',
      'Sentiment analysis',
      'Language modeling',
      'Speech recognition and synthesis',
      'Translation',
      'Azure AI Language service capabilities',
      'Azure AI Speech service capabilities',
    ],
    examTips: [
      'Key phrase extraction → main talking points; Entity recognition → people/places/dates/quantities.',
      'Sentiment analysis → positive/negative/neutral score.',
      'Speech-to-text = recognition; Text-to-speech = synthesis.',
      'Azure AI Language hosts text analytics, CLU, question answering; Azure AI Speech hosts STT/TTS/translation.',
      'Translator handles text translation across languages; Speech translation handles audio.',
    ],
    officialDocUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/language-service/overview',
  },
  {
    id: 'generative-ai',
    name: 'Describe features of generative AI workloads on Azure',
    weight: '20-25%',
    description: 'Identify generative AI features, scenarios, responsible AI considerations, and Azure services.',
    topics: [
      'Features of generative AI models',
      'Common scenarios for generative AI',
      'Responsible AI considerations for generative AI',
      'Azure AI Foundry features and capabilities',
      'Azure OpenAI service features and capabilities',
      'Azure AI Foundry model catalog',
    ],
    examTips: [
      'Generative AI creates NEW content (text, code, images) from natural-language prompts.',
      'LLMs use the Transformer architecture; tokens are the unit of text; embeddings capture meaning.',
      'Prompt engineering + grounding (RAG) improve relevance and reduce hallucinations.',
      'Azure OpenAI → GPT, DALL·E, embeddings with Azure security/compliance.',
      'Azure AI Foundry → build, evaluate, and deploy gen-AI apps; model catalog offers many models.',
    ],
    officialDocUrl: 'https://learn.microsoft.com/en-us/azure/ai-services/openai/overview',
  },
]
