import { buildQuestions, QSeed } from './_builder'

const seeds: QSeed[] = [
  // ── Containers: ACI ─────────────────────────────────────────────
  {
    id: 'cmp-001', topicId: 'aci', difficulty: 'easy',
    question: 'You need to run a single Linux container for a short batch job with per-second billing and no orchestration overhead. Which service is the best fit?',
    options: ['Azure Kubernetes Service', 'Azure Container Instances', 'Azure App Service', 'Azure Container Registry'],
    correctAnswer: 1,
    explanation: 'Azure Container Instances (ACI) runs single containers quickly with per-second billing and no orchestrator to manage — ideal for short, simple, or burst workloads.',
  },
  {
    id: 'cmp-002', topicId: 'aci', difficulty: 'medium',
    question: 'Which feature is NOT provided natively by Azure Container Instances?',
    options: ['Per-second billing', 'Mounting Azure Files shares', 'Built-in load balancing across instances', 'VNet integration'],
    correctAnswer: 2,
    explanation: 'ACI has no built-in load balancing. For autoscaling and load balancing across replicas, use Azure Container Apps or AKS.',
  },
  {
    id: 'cmp-003', topicId: 'aci', difficulty: 'medium',
    question: 'A container group in ACI lets you run multiple containers that share which of the following?',
    options: ['A Kubernetes namespace', 'The same lifecycle, network, and storage volumes', 'A single CPU core only', 'An App Service plan'],
    correctAnswer: 1,
    explanation: 'A container group is the top-level resource in ACI; containers in a group share a host, lifecycle, local network, and mounted volumes (similar to a Kubernetes pod).',
  },
  {
    id: 'cmp-004', topicId: 'aci', difficulty: 'hard',
    question: 'You must restart an ACI container automatically only if it exits with a non-zero exit code. Which restart policy should you set?',
    options: ['Always', 'OnFailure', 'Never', 'Manual'],
    correctAnswer: 1,
    explanation: 'The OnFailure restart policy restarts the container only when the process exits with a non-zero (failure) exit code. Always restarts regardless; Never does not restart.',
  },

  // ── Containers: ACR ─────────────────────────────────────────────
  {
    id: 'cmp-005', topicId: 'acr', difficulty: 'medium',
    question: 'You need geo-replication and private link support for your Azure Container Registry. Which SKU is required?',
    options: ['Basic', 'Standard', 'Premium', 'Free'],
    correctAnswer: 2,
    explanation: 'Geo-replication, private link, content trust, and the highest throughput are only available in the Premium ACR SKU.',
  },
  {
    id: 'cmp-006', topicId: 'acr', difficulty: 'medium',
    question: 'Which command builds a container image in the cloud without requiring a local Docker daemon?',
    options: ['docker build', 'az acr build', 'az acr import', 'az container create'],
    correctAnswer: 1,
    explanation: 'az acr build offloads the Docker build to ACR Tasks in the cloud, so no local Docker engine is needed, then pushes the image.',
  },
  {
    id: 'cmp-007', topicId: 'acr', difficulty: 'medium',
    question: 'For production, what is the recommended way to authenticate an Azure service to ACR?',
    options: ['Enable the admin user account', 'Use a managed identity with AcrPull role', 'Embed the registry password in app settings', 'Use anonymous pull'],
    correctAnswer: 1,
    explanation: 'A managed identity granted the AcrPull role avoids storing credentials. The admin account is for dev/test only and should be disabled in production.',
  },
  {
    id: 'cmp-008', topicId: 'acr', difficulty: 'hard',
    question: 'You want ACR to automatically rebuild an image whenever its base image receives a security patch. Which feature do you configure?',
    options: ['Webhooks', 'ACR Tasks with base image update triggers', 'Geo-replication', 'Content trust'],
    correctAnswer: 1,
    explanation: 'ACR Tasks support automatic build triggers on base image updates, git commits, or schedules, keeping images patched without manual rebuilds.',
  },

  // ── Containers: Container Apps ──────────────────────────────────
  {
    id: 'cmp-009', topicId: 'container-apps', difficulty: 'medium',
    question: 'Which capability uniquely distinguishes Azure Container Apps from Azure App Service for containers?',
    options: ['Custom domains', 'Scale to zero with KEDA-based event scaling', 'HTTPS ingress', 'Deployment of container images'],
    correctAnswer: 1,
    explanation: 'Container Apps can scale to zero and scale on KEDA event sources (queues, Event Hubs, HTTP). App Service cannot scale to zero.',
  },
  {
    id: 'cmp-010', topicId: 'container-apps', difficulty: 'hard',
    question: 'You need to send 20% of traffic to a new version of your container app while keeping 80% on the current version. What should you use?',
    options: ['Deployment slots', 'Multiple revisions with traffic splitting', 'Two separate App Service plans', 'ACI container groups'],
    correctAnswer: 1,
    explanation: 'Container Apps support multiple revisions; in multiple-revision mode you assign percentage weights to revisions for canary/blue-green and A/B testing.',
  },
  {
    id: 'cmp-011', topicId: 'container-apps', difficulty: 'medium',
    question: 'Which built-in framework in Container Apps provides service-to-service invocation, state management, and pub/sub for microservices?',
    options: ['KEDA', 'Dapr', 'Envoy', 'Helm'],
    correctAnswer: 1,
    explanation: 'Dapr (Distributed Application Runtime) is integrated into Container Apps and provides building blocks like service invocation, state, and pub/sub.',
  },
  {
    id: 'cmp-012', topicId: 'container-apps', difficulty: 'hard',
    question: 'A Container App should scale based on the number of messages in an Azure Service Bus queue. Which scaler type accomplishes this?',
    options: ['HTTP scaler', 'CPU scaler', 'A KEDA custom (azure-servicebus) scaler', 'Manual scaling only'],
    correctAnswer: 2,
    explanation: 'KEDA includes an azure-servicebus scaler; you configure a scale rule referencing the queue so replicas scale with message count, including to zero.',
  },

  // ── App Service: plans & scaling ────────────────────────────────
  {
    id: 'cmp-013', topicId: 'app-service', difficulty: 'easy',
    question: 'What is the difference between scaling up and scaling out an App Service?',
    options: ['Scaling up adds instances; scaling out changes tier', 'Scaling up changes the pricing tier; scaling out adds instances', 'They are identical', 'Scaling out is only manual'],
    correctAnswer: 1,
    explanation: 'Scaling up (vertical) changes the pricing tier for more CPU/RAM/features; scaling out (horizontal) increases the number of instances.',
  },
  {
    id: 'cmp-014', topicId: 'app-service', difficulty: 'medium',
    question: 'Which App Service plan tier is the minimum required to use deployment slots and autoscale?',
    options: ['Free', 'Shared', 'Basic', 'Standard'],
    correctAnswer: 3,
    explanation: 'Deployment slots and autoscale require Standard tier or higher. Free/Shared/Basic do not support deployment slots or rule-based autoscale.',
  },
  {
    id: 'cmp-015', topicId: 'app-service', difficulty: 'medium',
    question: 'You configure an autoscale rule to add an instance when average CPU exceeds 70% for 10 minutes. What kind of autoscale is this?',
    options: ['Schedule-based', 'Metric-based', 'Manual', 'Vertical'],
    correctAnswer: 1,
    explanation: 'Triggering scale-out on a metric threshold (CPU%) is metric-based autoscale. Schedule-based scales at set times regardless of load.',
  },
  {
    id: 'cmp-016', topicId: 'app-service', difficulty: 'hard',
    question: 'Multiple web apps run in the same App Service plan and one app consumes most of the CPU. What is the most direct fix?',
    options: ['Add more apps to the plan', 'Move the heavy app to its own App Service plan', 'Disable Always On', 'Switch to the Free tier'],
    correctAnswer: 1,
    explanation: 'Apps in the same plan share compute. Moving the resource-intensive app to a dedicated plan isolates it from the others.',
  },

  // ── App Service: TLS, domains, config ───────────────────────────
  {
    id: 'cmp-017', topicId: 'app-service', difficulty: 'medium',
    question: 'You must enforce that an App Service only accepts HTTPS connections. What do you configure?',
    options: ['Set HTTPS Only to On', 'Add an inbound NSG rule', 'Enable Always On', 'Create a deployment slot'],
    correctAnswer: 0,
    explanation: 'Enabling the "HTTPS Only" setting redirects all HTTP traffic to HTTPS at the App Service level.',
  },
  {
    id: 'cmp-018', topicId: 'app-service', difficulty: 'medium',
    question: 'Which option provides a free, auto-renewing TLS certificate for an App Service custom domain?',
    options: ['App Service Managed Certificate', 'A self-signed certificate', 'A wildcard from your CA only', 'Client certificate authentication'],
    correctAnswer: 0,
    explanation: 'App Service Managed Certificates are free and auto-renew, suitable for securing custom domains (with some limitations such as no wildcard for certain cases).',
  },
  {
    id: 'cmp-019', topicId: 'app-service', difficulty: 'hard',
    question: 'An App Service must require clients to present a certificate (mutual TLS). Which setting enables this?',
    options: ['HTTPS Only', 'Incoming client certificates (TLS mutual auth)', 'Managed identity', 'CORS'],
    correctAnswer: 1,
    explanation: 'Configuring "Incoming client certificates" (client certificate mode) enables mutual TLS, and the app validates the forwarded certificate.',
  },
  {
    id: 'cmp-020', topicId: 'app-service', difficulty: 'medium',
    question: 'Where should you store a database connection string for an App Service so it is not in source control and can be environment-specific?',
    options: ['In web.config committed to git', 'In App Service application settings / connection strings', 'In the Dockerfile', 'In a local.settings.json deployed with the app'],
    correctAnswer: 1,
    explanation: 'App settings and connection strings configured in App Service override config files, stay out of source control, and can be marked slot-specific.',
  },

  // ── App Service: slots ──────────────────────────────────────────
  {
    id: 'cmp-021', topicId: 'deployment-slots', difficulty: 'medium',
    question: 'What is the primary benefit of swapping a staging deployment slot into production?',
    options: ['Lower cost', 'Zero-downtime deployment with warm-up and easy rollback', 'Automatic database migration', 'Free TLS certificates'],
    correctAnswer: 1,
    explanation: 'Slot swaps pre-warm the target and exchange content/config so production updates without downtime; swapping back gives instant rollback.',
  },
  {
    id: 'cmp-022', topicId: 'deployment-slots', difficulty: 'hard',
    question: 'You have an app setting that must always remain tied to the production slot and NOT move during a swap. What must you do?',
    options: ['Nothing; settings never move', 'Mark it as a "deployment slot setting" (sticky)', 'Delete it before swapping', 'Store it in Key Vault only'],
    correctAnswer: 1,
    explanation: 'Marking a setting as a deployment slot (sticky) setting keeps it with its slot during a swap. Non-sticky settings travel with the content.',
  },
  {
    id: 'cmp-023', topicId: 'deployment-slots', difficulty: 'medium',
    question: 'Which of the following settings are sticky to a slot by default during a swap?',
    options: ['App settings marked as slot settings, custom domains, TLS bindings, and scale settings', 'All app settings', 'Only connection strings', 'Nothing is sticky'],
    correctAnswer: 0,
    explanation: 'Slot-specific settings (those marked sticky), custom domains, TLS/SSL bindings, scale settings, and Always On stay with the slot during a swap.',
  },

  // ── App Service: diagnostics/logging ────────────────────────────
  {
    id: 'cmp-024', topicId: 'app-service', difficulty: 'medium',
    question: 'You need to stream live application logs from an App Service while reproducing an issue. Which tool is most appropriate?',
    options: ['az webapp log tail', 'az acr build', 'az functionapp restart', 'az storage blob list'],
    correctAnswer: 0,
    explanation: 'az webapp log tail streams the live log output of an App Service, useful for real-time troubleshooting after enabling logging.',
  },
  {
    id: 'cmp-025', topicId: 'app-service', difficulty: 'hard',
    question: 'Application logging (filesystem) on App Service is automatically disabled after 12 hours. How do you retain logs longer term?',
    options: ['It is never disabled', 'Configure blob storage as the log destination', 'Use a deployment slot', 'Enable Always On'],
    correctAnswer: 1,
    explanation: 'Filesystem application logging is temporary (auto-disables after 12 hours). For retention, send logs to Azure Blob storage or use Azure Monitor/App Insights.',
  },

  // ── Functions: hosting plans ────────────────────────────────────
  {
    id: 'cmp-026', topicId: 'functions-hosting', difficulty: 'medium',
    question: 'Your Function app must avoid cold starts and integrate with a VNet, while still scaling dynamically. Which hosting plan fits best?',
    options: ['Consumption', 'Premium (Elastic Premium)', 'Free', 'Shared'],
    correctAnswer: 1,
    explanation: 'The Premium plan provides pre-warmed instances (no cold start), VNet connectivity, and unlimited execution duration with dynamic scaling.',
  },
  {
    id: 'cmp-027', topicId: 'functions-hosting', difficulty: 'medium',
    question: 'What is the default and maximum function timeout on the Consumption plan?',
    options: ['1 min default, 5 min max', '5 min default, 10 min max', 'Unlimited', '30 sec default, 2 min max'],
    correctAnswer: 1,
    explanation: 'On Consumption, the default timeout is 5 minutes and the maximum is 10 minutes. Longer workloads need Premium/Dedicated or Durable Functions.',
  },
  {
    id: 'cmp-028', topicId: 'functions-hosting', difficulty: 'easy',
    question: 'Which Functions hosting plan scales to zero and bills per execution?',
    options: ['Dedicated (App Service)', 'Premium', 'Consumption', 'Isolated'],
    correctAnswer: 2,
    explanation: 'The Consumption plan is truly serverless: it scales to zero when idle and you pay only for executions and resource consumption.',
  },
  {
    id: 'cmp-029', topicId: 'functions-hosting', difficulty: 'hard',
    question: 'You already run an App Service plan that is underutilized and want predictable cost for a few functions. Which plan should you choose?',
    options: ['Consumption', 'Premium', 'Dedicated (App Service plan)', 'Flex Consumption'],
    correctAnswer: 2,
    explanation: 'Running Functions on an existing App Service (Dedicated) plan reuses paid-for compute and gives predictable, flat cost.',
  },

  // ── Functions: triggers & bindings ──────────────────────────────
  {
    id: 'cmp-030', topicId: 'functions-bindings', difficulty: 'easy',
    question: 'How many triggers can a single Azure Function have?',
    options: ['Exactly one', 'Zero or one', 'Up to two', 'Unlimited'],
    correctAnswer: 0,
    explanation: 'A function must have exactly one trigger. It can have zero or more additional input and output bindings.',
  },
  {
    id: 'cmp-031', topicId: 'functions-bindings', difficulty: 'medium',
    question: 'Which binding direction writes data produced by a function to an external service such as a queue or Cosmos DB?',
    options: ['Trigger', 'Input binding', 'Output binding', 'Middleware binding'],
    correctAnswer: 2,
    explanation: 'Output bindings send the function results to a destination (queue, blob, Cosmos DB, etc.) declaratively, without manual SDK code.',
  },
  {
    id: 'cmp-032', topicId: 'functions-bindings', difficulty: 'hard',
    question: 'You need a Blob-triggered function with the lowest possible latency at scale. What should you use instead of the standard Blob trigger?',
    options: ['Timer trigger', 'Event Grid trigger for Blob events', 'HTTP trigger', 'Queue trigger'],
    correctAnswer: 1,
    explanation: 'The classic Blob trigger uses polling and can lag at scale. An Event Grid trigger reacting to Blob Created events provides near real-time, scalable delivery.',
  },
  {
    id: 'cmp-033', topicId: 'functions-bindings', difficulty: 'medium',
    question: 'A Timer-triggered function uses the NCRONTAB expression "0 */5 * * * *". How often does it run?',
    options: ['Every 5 seconds', 'Every 5 minutes', 'Every 5 hours', 'At 5 AM daily'],
    correctAnswer: 1,
    explanation: 'Azure Functions NCRONTAB has 6 fields ({second} {minute} {hour} {day} {month} {day-of-week}). "0 */5 * * * *" fires at second 0 every 5 minutes.',
  },
  {
    id: 'cmp-034', topicId: 'functions-bindings', difficulty: 'medium',
    question: 'In a function binding, the "Connection" property typically references what?',
    options: ['A hard-coded connection string', 'The name of an application setting that holds the connection', 'A managed identity object id', 'The function name'],
    correctAnswer: 1,
    explanation: 'The Connection property names an app setting (e.g. "StorageConn") that contains the connection string or identity-based config — never the literal secret.',
  },
  {
    id: 'cmp-035', topicId: 'functions-bindings', difficulty: 'hard',
    question: 'Which trigger is backed by the Azure Cosmos DB change feed?',
    options: ['Cosmos DB output binding', 'Cosmos DB trigger', 'Event Hub trigger', 'Service Bus trigger'],
    correctAnswer: 1,
    explanation: 'The Azure Functions Cosmos DB trigger listens to the change feed and invokes the function for inserted/updated items.',
  },

  // ── Functions: Durable ──────────────────────────────────────────
  {
    id: 'cmp-036', topicId: 'durable-functions', difficulty: 'medium',
    question: 'In Durable Functions, which function type defines the workflow and must be deterministic?',
    options: ['Client function', 'Orchestrator function', 'Activity function', 'Entity function'],
    correctAnswer: 1,
    explanation: 'The orchestrator function defines the workflow and must be deterministic (no DateTime.Now, random, or direct I/O) because it replays history.',
  },
  {
    id: 'cmp-037', topicId: 'durable-functions', difficulty: 'hard',
    question: 'You must run several independent activities in parallel and then aggregate their results. Which Durable Functions pattern applies?',
    options: ['Function chaining', 'Fan-out/fan-in', 'Monitor', 'Human interaction'],
    correctAnswer: 1,
    explanation: 'Fan-out/fan-in runs activities concurrently and then waits for all to complete to aggregate results.',
  },
  {
    id: 'cmp-038', topicId: 'durable-functions', difficulty: 'hard',
    question: 'A workflow must pause until a manager approves a request, with a 72-hour timeout. Which Durable pattern is this?',
    options: ['Async HTTP API', 'Monitor', 'Human interaction (wait for external event)', 'Function chaining'],
    correctAnswer: 2,
    explanation: 'The human interaction pattern waits for an external event (the approval) and combines it with a durable timer to enforce the timeout.',
  },
  {
    id: 'cmp-039', topicId: 'durable-functions', difficulty: 'medium',
    question: 'Why must orchestrator code avoid calling DateTime.Now or generating random numbers directly?',
    options: ['It is slower', 'Orchestrator code replays and must be deterministic', 'It costs more RUs', 'It breaks bindings'],
    correctAnswer: 1,
    explanation: 'Orchestrators replay their execution history to rebuild state, so any non-deterministic call would produce inconsistent results. Use context APIs (e.g. CurrentUtcDateTime).',
  },

  // ── Mixed / scenario compute ────────────────────────────────────
  {
    id: 'cmp-040', topicId: 'compute-choosing', difficulty: 'hard',
    scenario: 'A startup runs an event-driven image-processing pipeline. Each upload to Blob storage should trigger short-lived processing, and cost must be minimal during idle periods.',
    question: 'Which compute option best matches these requirements?',
    options: ['AKS cluster running 24/7', 'Azure Functions on the Consumption plan', 'A Standard App Service plan with Always On', 'A dedicated VM scale set'],
    correctAnswer: 1,
    explanation: 'Event-driven, short-lived, scale-to-zero, pay-per-execution work is the textbook case for Functions on the Consumption plan.',
  },
  {
    id: 'cmp-041', topicId: 'compute-choosing', difficulty: 'medium',
    scenario: 'A team needs to deploy several containerized microservices that communicate via pub/sub and must scale to zero overnight.',
    question: 'Which platform should they use?',
    options: ['Azure Container Instances', 'Azure Container Apps', 'Azure App Service (Windows)', 'Azure Batch'],
    correctAnswer: 1,
    explanation: 'Container Apps support microservices with Dapr pub/sub, KEDA scaling, and scale-to-zero — exactly these requirements.',
  },
  {
    id: 'cmp-042', topicId: 'app-service', difficulty: 'medium',
    question: 'Which deployment method allows zero-downtime releases by deploying to a non-production target first?',
    options: ['FTP deploy to production', 'Deploy to a staging slot then swap', 'Restart the app after deploy', 'Use the Free tier'],
    correctAnswer: 1,
    explanation: 'Deploying to a staging slot and swapping provides zero-downtime releases and instant rollback by swapping back.',
  },
  {
    id: 'cmp-043', topicId: 'functions-bindings', difficulty: 'medium',
    question: 'Which file defines runtime behavior (such as the function timeout and logging) for an Azure Functions app?',
    options: ['local.settings.json', 'host.json', 'function.json', 'appsettings.json'],
    correctAnswer: 1,
    explanation: 'host.json configures global runtime behavior. function.json defines a single function\'s bindings; local.settings.json holds local-only settings.',
  },
  {
    id: 'cmp-044', topicId: 'functions-bindings', difficulty: 'easy',
    question: 'Which file holds local development settings and should NOT be deployed to Azure?',
    options: ['host.json', 'function.json', 'local.settings.json', 'proxies.json'],
    correctAnswer: 2,
    explanation: 'local.settings.json contains local app settings/secrets and is excluded from deployment by default.',
  },
  {
    id: 'cmp-045', topicId: 'container-apps', difficulty: 'medium',
    question: 'In Container Apps single revision mode, what happens when you deploy a new container image?',
    options: ['Both old and new revisions receive traffic', 'A new revision replaces the old one and receives all traffic', 'Traffic is split 50/50 automatically', 'Nothing changes until you swap'],
    correctAnswer: 1,
    explanation: 'In single revision mode, a new revision becomes active and takes 100% of traffic, deactivating the previous revision.',
  },
  {
    id: 'cmp-046', topicId: 'aci', difficulty: 'medium',
    question: 'Which command creates an ACI container exposing port 80 with a public DNS name?',
    options: ['az webapp create', 'az container create --ports 80 --dns-name-label', 'az acr build', 'az containerapp create'],
    correctAnswer: 1,
    explanation: 'az container create with --ports and --dns-name-label provisions an ACI container with a public FQDN.',
  },
  {
    id: 'cmp-047', topicId: 'app-service', difficulty: 'hard',
    question: 'You want an App Service to keep a single instance always loaded so the first request is not slow. Which setting do you enable?',
    options: ['HTTPS Only', 'Always On', 'ARR Affinity', 'Client certificates'],
    correctAnswer: 1,
    explanation: 'Always On keeps the app loaded (prevents unloading after idle), avoiding cold-start latency. It also keeps continuous WebJobs/Timer triggers running.',
  },
  {
    id: 'cmp-048', topicId: 'app-service', difficulty: 'medium',
    question: 'A web app uses session affinity but you scaled out and want requests distributed evenly without sticky sessions. What should you do?',
    options: ['Enable ARR Affinity', 'Disable ARR Affinity (session affinity cookie)', 'Enable Always On', 'Add a deployment slot'],
    correctAnswer: 1,
    explanation: 'ARR Affinity pins a client to one instance via a cookie. Disable it for stateless apps to balance load across all instances.',
  },
  {
    id: 'cmp-049', topicId: 'functions-hosting', difficulty: 'medium',
    question: 'Which statement about the Flex Consumption plan for Functions is correct?',
    options: ['It cannot use VNet integration', 'It supports fast scaling, VNet integration, and per-instance concurrency control', 'It only runs Windows', 'It has a fixed single instance'],
    correctAnswer: 1,
    explanation: 'Flex Consumption combines fast/dynamic scaling with VNet integration and configurable per-instance concurrency.',
  },
  {
    id: 'cmp-050', topicId: 'durable-functions', difficulty: 'medium',
    question: 'Which Durable Functions pattern exposes a long-running operation with a status endpoint clients can poll?',
    options: ['Function chaining', 'Async HTTP API', 'Fan-out/fan-in', 'Monitor'],
    correctAnswer: 1,
    explanation: 'The async HTTP API pattern starts an orchestration and returns status query/management URLs clients poll until completion.',
  },
  {
    id: 'cmp-051', topicId: 'acr', difficulty: 'easy',
    question: 'What does ACR primarily store?',
    options: ['Function code', 'Container images and OCI artifacts', 'Blob data', 'Key Vault secrets'],
    correctAnswer: 1,
    explanation: 'Azure Container Registry is a managed private registry for Docker/OCI container images and related artifacts.',
  },
  {
    id: 'cmp-052', topicId: 'app-service', difficulty: 'hard',
    scenario: 'An app on a Standard plan experiences predictable daily traffic spikes between 9 AM and 5 PM.',
    question: 'What is the most cost-effective scaling strategy?',
    options: ['Manually scale up the tier permanently', 'Configure schedule-based autoscale to add instances during business hours', 'Run on the Free tier', 'Disable autoscale'],
    correctAnswer: 1,
    explanation: 'Schedule-based autoscale adds instances during known peak hours and scales in afterward, optimizing cost for predictable patterns.',
  },
  {
    id: 'cmp-053', topicId: 'functions-bindings', difficulty: 'hard',
    question: 'You need a function to read a blob whose name comes from a queue message, then write a result to Cosmos DB. How many bindings (excluding the trigger) are involved at minimum?',
    options: ['Zero', 'One', 'Two (a blob input binding and a Cosmos DB output binding)', 'Three'],
    correctAnswer: 2,
    explanation: 'The queue is the trigger; a blob input binding reads the blob and a Cosmos DB output binding writes the result — two bindings besides the trigger.',
  },
  {
    id: 'cmp-054', topicId: 'container-apps', difficulty: 'medium',
    question: 'Which ingress option exposes a Container App only within its virtual network?',
    options: ['External ingress', 'Internal ingress', 'Public ingress', 'No ingress is possible'],
    correctAnswer: 1,
    explanation: 'Internal ingress restricts access to within the Container Apps environment/VNet; external ingress exposes it to the internet.',
  },
  {
    id: 'cmp-055', topicId: 'app-service', difficulty: 'medium',
    question: 'Which CLI command deploys a ZIP package to an App Service?',
    options: ['az webapp deploy --src-path app.zip', 'az acr import', 'az functionapp config', 'az storage blob upload'],
    correctAnswer: 0,
    explanation: 'az webapp deploy (ZIP deploy) pushes a packaged build to App Service, which then runs it.',
  },
  {
    id: 'cmp-056', topicId: 'functions-hosting', difficulty: 'easy',
    question: 'Azure Functions requires an associated storage account primarily for what?',
    options: ['Hosting the web UI', 'Managing triggers, logging, and state coordination', 'Storing TLS certificates', 'Running the Dapr sidecar'],
    correctAnswer: 1,
    explanation: 'A Functions app needs a storage account for trigger management, checkpointing, logs, and internal coordination.',
  },
  {
    id: 'cmp-057', topicId: 'compute-choosing', difficulty: 'medium',
    question: 'Which option provides the MOST control over Kubernetes networking, upgrades, and node pools?',
    options: ['Azure Container Instances', 'Azure Container Apps', 'Azure Kubernetes Service (AKS)', 'Azure App Service'],
    correctAnswer: 2,
    explanation: 'AKS gives full control over the Kubernetes cluster, including node pools, networking, and upgrade cadence; ACA abstracts most of this away.',
  },
  {
    id: 'cmp-058', topicId: 'deployment-slots', difficulty: 'medium',
    question: 'What is auto swap used for in App Service slots?',
    options: ['Automatically swapping a slot into production after a successful deployment', 'Automatically scaling out', 'Rotating TLS certificates', 'Deleting old slots'],
    correctAnswer: 0,
    explanation: 'Auto swap automatically swaps a source slot into the target (e.g., production) once deployment and warm-up succeed, enabling continuous deployment.',
  },
  {
    id: 'cmp-059', topicId: 'functions-bindings', difficulty: 'hard',
    question: 'In the isolated worker model for .NET Functions, how are output bindings typically returned?',
    options: ['Via out parameters only', 'Through a return value or an output binding type/attribute on the return object', 'Only by calling the SDK manually', 'They are not supported'],
    correctAnswer: 1,
    explanation: 'The isolated worker model returns outputs via the function return value (or a multi-output type), since out parameters are an in-process construct.',
  },
  {
    id: 'cmp-060', topicId: 'app-service', difficulty: 'medium',
    question: 'You want to run a Linux container image directly in App Service. Which is required?',
    options: ['A Windows plan', 'A Linux App Service plan (Web App for Containers)', 'AKS', 'A storage account only'],
    correctAnswer: 1,
    explanation: 'Web App for Containers runs custom container images on a Linux App Service plan, pulling from ACR or another registry.',
  },
  {
    id: 'cmp-061', topicId: 'aci', difficulty: 'hard',
    question: 'To pull a private image from ACR into ACI without an admin account, what should you configure?',
    options: ['Anonymous pull', 'A managed identity or service principal with AcrPull', 'A SAS token', 'A storage key'],
    correctAnswer: 1,
    explanation: 'ACI can use a managed identity or service principal granted AcrPull to authenticate to a private registry securely.',
  },
  {
    id: 'cmp-062', topicId: 'durable-functions', difficulty: 'medium',
    question: 'Which Durable Functions pattern periodically checks a resource until a condition is met or it times out?',
    options: ['Monitor', 'Fan-out/fan-in', 'Function chaining', 'Async HTTP API'],
    correctAnswer: 0,
    explanation: 'The monitor pattern uses a durable timer loop to poll a resource on a schedule until a condition is satisfied or a deadline passes.',
  },
  {
    id: 'cmp-063', topicId: 'functions-bindings', difficulty: 'medium',
    question: 'An HTTP-triggered function should require a function-level API key. Which authorization level achieves this?',
    options: ['Anonymous', 'Function', 'Admin', 'System'],
    correctAnswer: 1,
    explanation: 'The "Function" authorization level requires a function key in the request. Anonymous needs no key; Admin requires the host master key.',
  },
  {
    id: 'cmp-064', topicId: 'app-service', difficulty: 'easy',
    question: 'Which logging integration gives the richest application performance monitoring for an App Service?',
    options: ['FTP logs', 'Application Insights', 'Console.log only', 'NSG flow logs'],
    correctAnswer: 1,
    explanation: 'Application Insights provides request, dependency, exception, and performance telemetry, far beyond basic filesystem logs.',
  },
  {
    id: 'cmp-065', topicId: 'container-apps', difficulty: 'hard',
    question: 'A Container App scale rule sets minReplicas=0 and maxReplicas=10 with an HTTP scaler. What occurs when no requests arrive for a while?',
    options: ['It stays at 10 replicas', 'It scales down to 0 replicas', 'It throws an error', 'It scales up to maxReplicas'],
    correctAnswer: 1,
    explanation: 'With minReplicas=0 and an HTTP scaler, the app scales to zero when idle and scales out again on incoming requests.',
  },
  {
    id: 'cmp-066', topicId: 'functions-hosting', difficulty: 'medium',
    question: 'Which statement about cold starts is accurate?',
    options: ['Premium plans eliminate cold starts via pre-warmed instances', 'Consumption never has cold starts', 'Cold starts only affect HTTP triggers', 'Dedicated plans always have cold starts'],
    correctAnswer: 0,
    explanation: 'Premium plans keep pre-warmed instances ready, avoiding cold starts that can occur on the Consumption plan after idle periods.',
  },
  {
    id: 'cmp-067', topicId: 'acr', difficulty: 'medium',
    question: 'Which ACR feature signs images so consumers can verify their integrity and publisher?',
    options: ['Geo-replication', 'Content trust (Docker Notary)', 'Webhooks', 'Tasks'],
    correctAnswer: 1,
    explanation: 'Content trust enables image signing and verification so only trusted, signed images are pulled.',
  },
  {
    id: 'cmp-068', topicId: 'app-service', difficulty: 'hard',
    scenario: 'A regulated workload requires network isolation, dedicated compute, and high scale for App Service.',
    question: 'Which App Service plan tier should you choose?',
    options: ['Free', 'Basic', 'Standard', 'Isolated (App Service Environment)'],
    correctAnswer: 3,
    explanation: 'The Isolated tier (App Service Environment) provides dedicated, network-isolated compute with high scale for regulated/secure workloads.',
  },
  {
    id: 'cmp-069', topicId: 'functions-bindings', difficulty: 'medium',
    question: 'Which trigger should you use to run a function on a recurring schedule?',
    options: ['HTTP trigger', 'Timer trigger', 'Queue trigger', 'Blob trigger'],
    correctAnswer: 1,
    explanation: 'The Timer trigger uses an NCRONTAB schedule to run functions at recurring intervals.',
  },
  {
    id: 'cmp-070', topicId: 'compute-choosing', difficulty: 'medium',
    question: 'Which compute service is least appropriate for a long-running, always-on background process that needs persistent state?',
    options: ['AKS', 'App Service (Dedicated)', 'Azure Functions on Consumption', 'Azure Container Apps'],
    correctAnswer: 2,
    explanation: 'Consumption Functions have execution time limits and scale to zero, making them poor for always-on, long-running stateful processes (use Durable, Premium, or a dedicated host).',
  },
  {
    id: 'cmp-071', topicId: 'container-apps', difficulty: 'medium',
    question: 'Where do you store secrets for a Container App so they can be referenced by environment variables securely?',
    options: ['In the Dockerfile', 'In Container Apps secrets (or referenced from Key Vault)', 'In plain app settings only', 'In the image tag'],
    correctAnswer: 1,
    explanation: 'Container Apps support secrets that environment variables can reference; you can also pull from Key Vault using a managed identity.',
  },
  {
    id: 'cmp-072', topicId: 'app-service', difficulty: 'easy',
    question: 'Which command tails the deployment logs to diagnose a failed deployment?',
    options: ['az webapp log deployment show', 'az acr login', 'az storage account create', 'az group delete'],
    correctAnswer: 0,
    explanation: 'az webapp log deployment show retrieves deployment logs to diagnose build/deploy failures.',
  },
  {
    id: 'cmp-073', topicId: 'durable-functions', difficulty: 'hard',
    question: 'Which Durable Functions component does the actual unit of work and can be non-deterministic?',
    options: ['Orchestrator', 'Activity function', 'Client function', 'Durable timer'],
    correctAnswer: 1,
    explanation: 'Activity functions perform the work (I/O, calls) and may be non-deterministic; orchestrators must remain deterministic.',
  },
  {
    id: 'cmp-074', topicId: 'functions-bindings', difficulty: 'medium',
    question: 'What is the purpose of an input binding in Azure Functions?',
    options: ['To start the function', 'To declaratively read data from a source into the function', 'To write data out', 'To define the schedule'],
    correctAnswer: 1,
    explanation: 'Input bindings declaratively fetch data (e.g., a specific blob or Cosmos document) and pass it to the function without manual SDK calls.',
  },
  {
    id: 'cmp-075', topicId: 'compute-choosing', difficulty: 'hard',
    scenario: 'You need to expose a REST API with built-in HTTPS, autoscaling, deployment slots, and easy CI/CD, without managing containers or Kubernetes.',
    question: 'Which service is the best fit?',
    options: ['Azure Container Instances', 'Azure App Service (Web App)', 'AKS', 'Azure Batch'],
    correctAnswer: 1,
    explanation: 'App Service provides managed hosting with HTTPS, autoscale, deployment slots, and integrated CI/CD without container/Kubernetes management.',
  },
]

export const computeQuestions = buildQuestions('develop-compute', 'Develop Azure compute solutions', seeds)
