import { buildQuestions, QSeed } from './_builder'

const seeds: QSeed[] = [
  // ── Messaging choice ────────────────────────────────────────────
  {
    id: 'con-001', topicId: 'messaging-choice', difficulty: 'medium',
    question: 'You must ingest millions of telemetry events per second from IoT devices into a big-data pipeline. Which service fits best?',
    options: ['Azure Service Bus', 'Azure Event Hubs', 'Azure Queue Storage', 'Azure Event Grid'],
    correctAnswer: 1,
    explanation: 'Event Hubs is built for high-throughput event/telemetry streaming (millions/sec) and integrates with big-data pipelines.',
  },
  {
    id: 'con-002', topicId: 'messaging-choice', difficulty: 'medium',
    question: 'A system must reliably process business transactions with ordering, dead-lettering, and transactions. Which service is correct?',
    options: ['Event Grid', 'Event Hubs', 'Service Bus', 'Queue Storage'],
    correctAnswer: 2,
    explanation: 'Service Bus is the enterprise message broker with ordering (sessions), dead-lettering, duplicate detection, and transactions.',
  },
  {
    id: 'con-003', topicId: 'messaging-choice', difficulty: 'medium',
    question: 'You want to react to discrete events (e.g., a blob was created) and fan out to multiple handlers. Which service is designed for this?',
    options: ['Event Grid', 'Event Hubs', 'Service Bus', 'Queue Storage'],
    correctAnswer: 0,
    explanation: 'Event Grid routes discrete events to multiple subscribers with filtering — ideal for reactive, event-driven architectures.',
  },
  {
    id: 'con-004', topicId: 'messaging-choice', difficulty: 'easy',
    question: 'Which service provides the simplest, cheapest queue for basic decoupling at massive scale?',
    options: ['Service Bus', 'Event Hubs', 'Queue Storage', 'Event Grid'],
    correctAnswer: 2,
    explanation: 'Azure Queue Storage is a simple, low-cost queue for decoupling components, supporting millions of messages up to 64 KB each.',
  },
  {
    id: 'con-005', topicId: 'messaging-choice', difficulty: 'hard',
    question: 'What is the core conceptual difference between an "event" and a "message"?',
    options: ['They are identical', 'An event is a lightweight notification that something happened; a message contains data with intent that a consumer must process', 'A message is smaller', 'An event always requires a response'],
    correctAnswer: 1,
    explanation: 'Events are lightweight signals (publisher does not expect processing); messages carry data with an explicit intent to be processed by a consumer.',
  },
  {
    id: 'con-006', topicId: 'messaging-choice', difficulty: 'hard',
    scenario: 'An e-commerce platform must notify several independent subsystems whenever an order is placed, with each reacting in real time.',
    question: 'Which service best enables this fan-out of discrete events?',
    options: ['Event Hubs', 'Event Grid', 'Queue Storage', 'A single Service Bus queue'],
    correctAnswer: 1,
    explanation: 'Event Grid publishes the "order placed" event and fans out to multiple subscribers (functions, logic apps, webhooks) reacting in real time.',
  },

  // ── API Management ──────────────────────────────────────────────
  {
    id: 'con-007', topicId: 'apim', difficulty: 'easy',
    question: 'What is the primary role of Azure API Management?',
    options: ['Store secrets', 'Publish, secure, transform, and monitor APIs through a gateway', 'Run containers', 'Cache files'],
    correctAnswer: 1,
    explanation: 'APIM is an API gateway that publishes APIs and applies security, transformation, throttling, and observability across backends.',
  },
  {
    id: 'con-008', topicId: 'apim', difficulty: 'medium',
    question: 'In which policy scope does a rate-limit typically run to throttle inbound requests before they reach the backend?',
    options: ['Outbound', 'Backend', 'Inbound', 'On-error'],
    correctAnswer: 2,
    explanation: 'Throttling/rate-limit policies run in the inbound scope so requests are limited before being forwarded to the backend.',
  },
  {
    id: 'con-009', topicId: 'apim', difficulty: 'medium',
    question: 'What does the <base /> element do inside an APIM policy section?',
    options: ['Deletes the request', 'Inherits and runs the policy defined at the parent scope', 'Sets the backend URL', 'Caches the response'],
    correctAnswer: 1,
    explanation: '<base /> executes the policies inherited from the parent scope (global > product > API > operation) at that point.',
  },
  {
    id: 'con-010', topicId: 'apim', difficulty: 'hard',
    question: 'Which APIM policy validates a JWT access token on inbound requests?',
    options: ['rate-limit', 'validate-jwt', 'set-header', 'mock-response'],
    correctAnswer: 1,
    explanation: 'The validate-jwt policy checks the token signature, audience, issuer, and required claims to authorize requests.',
  },
  {
    id: 'con-011', topicId: 'apim', difficulty: 'medium',
    question: 'How do you control which consumers can call an API in APIM?',
    options: ['By IP only', 'Via products and subscription keys', 'By blob metadata', 'By TTL'],
    correctAnswer: 1,
    explanation: 'APIM groups APIs into products; subscriptions issue keys that consumers must present, gating access.',
  },
  {
    id: 'con-012', topicId: 'apim', difficulty: 'hard',
    question: 'Which APIM tier supports multi-region deployment and VNet integration?',
    options: ['Consumption', 'Developer', 'Basic', 'Premium'],
    correctAnswer: 3,
    explanation: 'The Premium tier supports multi-region deployment, VNet integration, and higher scale; Developer has no SLA.',
  },
  {
    id: 'con-013', topicId: 'apim', difficulty: 'medium',
    question: 'Which APIM policy caches backend responses to reduce load and latency?',
    options: ['cache-lookup and cache-store', 'validate-jwt', 'rate-limit-by-key', 'rewrite-uri'],
    correctAnswer: 0,
    explanation: 'cache-lookup (inbound) and cache-store (outbound) enable response caching in APIM to serve repeated requests faster.',
  },
  {
    id: 'con-014', topicId: 'apim', difficulty: 'medium',
    question: 'Which APIM policy modifies the request URL before sending it to the backend?',
    options: ['set-header', 'rewrite-uri', 'cache-store', 'return-response'],
    correctAnswer: 1,
    explanation: 'rewrite-uri changes the request path/query that is forwarded to the backend, useful for mapping public to internal routes.',
  },
  {
    id: 'con-015', topicId: 'apim', difficulty: 'hard',
    question: 'You want APIM to return a canned response for testing before the backend exists. Which policy do you use?',
    options: ['mock-response', 'validate-jwt', 'rate-limit', 'forward-request'],
    correctAnswer: 0,
    explanation: 'The mock-response policy returns a sample response defined in the API, enabling front-end development before the backend is ready.',
  },
  {
    id: 'con-016', topicId: 'apim', difficulty: 'medium',
    question: 'Which component of APIM lets external developers discover and test your APIs?',
    options: ['The gateway', 'The developer portal', 'The backend', 'The action group'],
    correctAnswer: 1,
    explanation: 'The developer portal is the customizable site where consumers browse documentation, get keys, and try APIs.',
  },
  {
    id: 'con-017', topicId: 'apim', difficulty: 'hard',
    question: 'Which policy restricts calls based on the caller IP address?',
    options: ['ip-filter', 'set-backend-service', 'cache-lookup', 'set-variable'],
    correctAnswer: 0,
    explanation: 'The ip-filter policy allows or denies requests based on the client IP address or range.',
  },
  {
    id: 'con-018', topicId: 'apim', difficulty: 'medium',
    question: 'Which policy adds or overrides an HTTP header on the request or response?',
    options: ['set-header', 'rate-limit', 'validate-jwt', 'mock-response'],
    correctAnswer: 0,
    explanation: 'set-header adds, sets, or removes headers in the inbound request or outbound response.',
  },
  {
    id: 'con-019', topicId: 'apim', difficulty: 'hard',
    question: 'rate-limit vs quota policies differ how?',
    options: ['They are identical', 'rate-limit caps calls over a short renewal window; quota caps total calls/data over a longer period (e.g., per month)', 'quota is per second only', 'rate-limit applies to storage'],
    correctAnswer: 1,
    explanation: 'rate-limit throttles bursts over a short window (e.g., per minute); quota enforces a longer-term volume cap (e.g., per subscription per month).',
  },
  {
    id: 'con-020', topicId: 'apim', difficulty: 'medium',
    question: 'How can APIM authenticate to a backend using a managed identity?',
    options: ['It cannot', 'Use the authentication-managed-identity policy to obtain a token for the backend', 'Embed a password', 'Use a SAS'],
    correctAnswer: 1,
    explanation: 'The authentication-managed-identity policy lets APIM acquire an Entra token via its managed identity to call a protected backend.',
  },
  {
    id: 'con-021', topicId: 'apim', difficulty: 'easy',
    question: 'Which APIM tier is serverless with per-call billing and automatic scaling?',
    options: ['Consumption', 'Premium', 'Developer', 'Isolated'],
    correctAnswer: 0,
    explanation: 'The Consumption tier is serverless, scales automatically, and bills per call — good for lightweight or sporadic workloads.',
  },
  {
    id: 'con-022', topicId: 'apim', difficulty: 'hard',
    scenario: 'Partners must call your API but you need to enforce 1000 calls/month per partner and validate their identity tokens.',
    question: 'Which combination achieves this?',
    options: ['rate-limit only', 'quota-by-key for the monthly cap plus validate-jwt for identity', 'ip-filter only', 'mock-response'],
    correctAnswer: 1,
    explanation: 'quota-by-key enforces the per-partner monthly limit while validate-jwt verifies each partner\'s token.',
  },

  // ── Event Grid ──────────────────────────────────────────────────
  {
    id: 'con-023', topicId: 'event-grid', difficulty: 'easy',
    question: 'Which delivery model does Event Grid use to send events to handlers?',
    options: ['Pull only', 'Push (with retries)', 'Polling', 'Batch download'],
    correctAnswer: 1,
    explanation: 'Event Grid pushes events to subscribed handlers and retries on failure, unlike pull-based services.',
  },
  {
    id: 'con-024', topicId: 'event-grid', difficulty: 'medium',
    question: 'When you subscribe a webhook endpoint to Event Grid, what must the endpoint do first?',
    options: ['Send an email', 'Complete a validation handshake (echo the validation code)', 'Open a port 22', 'Store a SAS'],
    correctAnswer: 1,
    explanation: 'Event Grid sends a subscription validation event; the webhook must echo the validation code to prove ownership before receiving events.',
  },
  {
    id: 'con-025', topicId: 'event-grid', difficulty: 'medium',
    question: 'What delivery guarantee does Event Grid provide?',
    options: ['Exactly-once', 'At-least-once with retries', 'At-most-once', 'No delivery guarantee'],
    correctAnswer: 1,
    explanation: 'Event Grid guarantees at-least-once delivery, retrying failed deliveries with an exponential back-off and optional dead-lettering.',
  },
  {
    id: 'con-026', topicId: 'event-grid', difficulty: 'hard',
    question: 'How do you capture events that Event Grid could not deliver after all retries?',
    options: ['They are lost', 'Configure a dead-letter destination (e.g., a storage container)', 'Increase TTL only', 'Use a SAS'],
    correctAnswer: 1,
    explanation: 'Configuring a dead-letter location (a Blob container) stores undeliverable events for later inspection/reprocessing.',
  },
  {
    id: 'con-027', topicId: 'event-grid', difficulty: 'medium',
    question: 'How can you ensure a subscriber only receives events of a certain type or subject?',
    options: ['You cannot filter', 'Apply event type and subject filters (or advanced filters) on the subscription', 'Use a SAS', 'Change consistency level'],
    correctAnswer: 1,
    explanation: 'Event subscriptions support filtering by event type, subject prefix/suffix, and advanced fields so handlers only get relevant events.',
  },
  {
    id: 'con-028', topicId: 'event-grid', difficulty: 'medium',
    question: 'Which of these is a valid Event Grid handler (destination)?',
    options: ['Azure Functions, Logic Apps, Webhooks, Service Bus, Event Hubs, Storage Queues', 'Only email', 'Only AKS', 'Only Cosmos DB'],
    correctAnswer: 0,
    explanation: 'Event Grid can deliver to many handler types: Functions, Logic Apps, webhooks, Service Bus, Event Hubs, Storage Queues, and more.',
  },
  {
    id: 'con-029', topicId: 'event-grid', difficulty: 'hard',
    question: 'A system topic in Event Grid represents what?',
    options: ['A custom application topic', 'Built-in events from an Azure service (e.g., Blob Storage)', 'A Service Bus topic', 'A Redis channel'],
    correctAnswer: 1,
    explanation: 'System topics are provided by Azure services to publish their events (e.g., Blob Created), while custom topics are for your own app events.',
  },
  {
    id: 'con-030', topicId: 'event-grid', difficulty: 'medium',
    question: 'Which schema options does Event Grid support for events?',
    options: ['Only XML', 'Event Grid schema and CloudEvents 1.0 schema', 'Only CSV', 'Only Avro'],
    correctAnswer: 1,
    explanation: 'Event Grid supports its native Event Grid schema and the open CloudEvents 1.0 schema for interoperability.',
  },
  {
    id: 'con-031', topicId: 'event-grid', difficulty: 'medium',
    question: 'What is the maximum recommended size and typical default retry duration concept for Event Grid events?',
    options: ['Events can be gigabytes with no retry', 'Events are small (up to 1 MB, billed per 64 KB) and retried with back-off up to a TTL (default 24h)', 'No size limit', 'Events never retry'],
    correctAnswer: 1,
    explanation: 'Event Grid events are small; delivery is retried with exponential back-off until success or the event time-to-live (default 24 hours) expires.',
  },

  // ── Event Hubs ──────────────────────────────────────────────────
  {
    id: 'con-032', topicId: 'event-hubs', difficulty: 'medium',
    question: 'In Event Hubs, what is the unit of parallelism and ordering?',
    options: ['Consumer group', 'Partition', 'Topic', 'Subscription'],
    correctAnswer: 1,
    explanation: 'Partitions provide parallelism and ordered streams; ordering is guaranteed only within a partition.',
  },
  {
    id: 'con-033', topicId: 'event-hubs', difficulty: 'medium',
    question: 'What does a consumer group in Event Hubs provide?',
    options: ['A separate queue', 'An independent view/position over the event stream for a set of consumers', 'A dead-letter queue', 'A cache'],
    correctAnswer: 1,
    explanation: 'A consumer group is an independent view of the stream, letting multiple downstream applications each read at their own pace/position.',
  },
  {
    id: 'con-034', topicId: 'event-hubs', difficulty: 'hard',
    question: 'How does an Event Hubs consumer track which events it has processed so it can resume after a failure?',
    options: ['Dead-lettering', 'Checkpointing (storing the offset, often in Blob storage)', 'TTL', 'Sessions'],
    correctAnswer: 1,
    explanation: 'Consumers checkpoint their position (offset/sequence number), commonly to Blob storage, to resume processing after restarts without reprocessing everything.',
  },
  {
    id: 'con-035', topicId: 'event-hubs', difficulty: 'medium',
    question: 'Which Event Hubs feature automatically archives the event stream to Blob Storage or Data Lake?',
    options: ['Capture', 'Sessions', 'Dead-lettering', 'Geo-replication'],
    correctAnswer: 0,
    explanation: 'Event Hubs Capture automatically writes streamed events to Blob Storage or Azure Data Lake for batch processing or archival.',
  },
  {
    id: 'con-036', topicId: 'event-hubs', difficulty: 'medium',
    question: 'Which protocol does Event Hubs expose that makes it compatible with Apache Kafka clients?',
    options: ['MQTT', 'Kafka protocol endpoint', 'SMTP', 'gRPC only'],
    correctAnswer: 1,
    explanation: 'Event Hubs offers a Kafka-compatible endpoint, so existing Kafka producers/consumers can use Event Hubs with minimal changes.',
  },
  {
    id: 'con-037', topicId: 'event-hubs', difficulty: 'hard',
    question: 'Ordering of events in Event Hubs is guaranteed at what scope?',
    options: ['Across the whole event hub', 'Within a single partition', 'Across all consumer groups', 'There is no ordering'],
    correctAnswer: 1,
    explanation: 'Event ordering is preserved within a partition only; to keep related events ordered, send them to the same partition (via a partition key).',
  },
  {
    id: 'con-038', topicId: 'event-hubs', difficulty: 'medium',
    question: 'How do you ensure related events (e.g., from one device) land in the same partition?',
    options: ['Random distribution', 'Specify a partition key when sending', 'Use sessions', 'Use dead-lettering'],
    correctAnswer: 1,
    explanation: 'Providing a partition key routes all events with that key to the same partition, preserving their relative order.',
  },
  {
    id: 'con-039', topicId: 'event-hubs', difficulty: 'medium',
    question: 'What controls the ingress/egress capacity of a standard Event Hubs namespace?',
    options: ['Throughput Units', 'Partitions only', 'Consumer groups', 'Sessions'],
    correctAnswer: 0,
    explanation: 'Throughput Units (TUs) define the capacity (MB/s and events/s) for ingress and egress in standard Event Hubs (Premium uses Processing Units).',
  },
  {
    id: 'con-040', topicId: 'event-hubs', difficulty: 'hard',
    question: 'Which SDK class simplifies partition-aware consumption and checkpointing in newer Event Hubs SDKs?',
    options: ['EventProcessorClient', 'QueueClient', 'SecretClient', 'BlobClient'],
    correctAnswer: 0,
    explanation: 'EventProcessorClient distributes partitions across consumers and manages checkpoints (e.g., via a Blob checkpoint store).',
  },

  // ── Service Bus ─────────────────────────────────────────────────
  {
    id: 'con-041', topicId: 'service-bus', difficulty: 'medium',
    question: 'Which Service Bus feature guarantees ordered, single-consumer processing for related messages?',
    options: ['Dead-lettering', 'Sessions', 'Duplicate detection', 'Auto-forwarding'],
    correctAnswer: 1,
    explanation: 'Sessions provide FIFO ordering and lock all messages of a session to a single consumer, preserving order for related messages.',
  },
  {
    id: 'con-042', topicId: 'service-bus', difficulty: 'medium',
    question: 'What is the dead-letter queue (DLQ) used for in Service Bus?',
    options: ['Faster delivery', 'Holding messages that cannot be processed or delivered (poison/expired)', 'Caching', 'Encryption'],
    correctAnswer: 1,
    explanation: 'The DLQ is a sub-queue holding messages that exceeded max delivery count, expired, or were explicitly dead-lettered for later inspection.',
  },
  {
    id: 'con-043', topicId: 'service-bus', difficulty: 'hard',
    question: 'Which receive mode locks a message so it can be processed and then explicitly completed (or abandoned)?',
    options: ['Receive-and-Delete', 'Peek-Lock', 'Auto-complete only', 'Broadcast'],
    correctAnswer: 1,
    explanation: 'Peek-Lock locks the message during processing; you call Complete on success or Abandon/Dead-letter on failure, ensuring at-least-once handling.',
  },
  {
    id: 'con-044', topicId: 'service-bus', difficulty: 'medium',
    question: 'Which Service Bus entity enables publish/subscribe with multiple subscribers receiving filtered copies of messages?',
    options: ['Queue', 'Topic with subscriptions', 'Relay', 'Namespace'],
    correctAnswer: 1,
    explanation: 'Topics with subscriptions implement pub/sub: each subscription can apply filters and receives its own copy of matching messages.',
  },
  {
    id: 'con-045', topicId: 'service-bus', difficulty: 'hard',
    question: 'A message goes to the DLQ for which of these reasons?',
    options: ['It was processed successfully', 'Exceeding max delivery count, TTL expiration, or explicit dead-lettering', 'Being read once', 'Having a partition key'],
    correctAnswer: 1,
    explanation: 'Messages dead-letter when they exceed the max delivery count, expire (TTL), or are explicitly dead-lettered (e.g., filter evaluation errors).',
  },
  {
    id: 'con-046', topicId: 'service-bus', difficulty: 'medium',
    question: 'Which Service Bus feature prevents the same message from being processed twice if a sender retries?',
    options: ['Duplicate detection', 'Sessions', 'Dead-lettering', 'Auto-forward'],
    correctAnswer: 0,
    explanation: 'Duplicate detection discards messages with a repeated MessageId within a configured time window, ensuring at-most-once enqueue.',
  },
  {
    id: 'con-047', topicId: 'service-bus', difficulty: 'medium',
    question: 'Which Service Bus tier provides dedicated resources, predictable performance, larger messages, and geo-disaster recovery?',
    options: ['Basic', 'Standard', 'Premium', 'Free'],
    correctAnswer: 2,
    explanation: 'Premium offers dedicated capacity, predictable latency, larger message sizes, and geo-DR; Basic lacks topics; Standard is shared.',
  },
  {
    id: 'con-048', topicId: 'service-bus', difficulty: 'hard',
    question: 'How do you delay a Service Bus message so it becomes available at a future time?',
    options: ['Use scheduled messages (ScheduledEnqueueTime)', 'Use a SAS', 'Use sessions only', 'It is impossible'],
    correctAnswer: 0,
    explanation: 'Scheduled messages set a ScheduledEnqueueTimeUtc so the message is enqueued and delivered at the specified future time.',
  },
  {
    id: 'con-049', topicId: 'service-bus', difficulty: 'medium',
    question: 'What does abandoning a message in Peek-Lock mode do?',
    options: ['Deletes it permanently', 'Releases the lock so the message becomes available again (incrementing delivery count)', 'Sends it to the DLQ immediately', 'Completes it'],
    correctAnswer: 1,
    explanation: 'Abandon releases the lock and returns the message to the queue for redelivery, increasing its delivery count (which can eventually dead-letter it).',
  },
  {
    id: 'con-050', topicId: 'service-bus', difficulty: 'hard',
    question: 'Which filter type on a Service Bus subscription lets you match on message properties using SQL-like expressions?',
    options: ['Correlation filter only', 'SQL filter', 'No filtering', 'Partition filter'],
    correctAnswer: 1,
    explanation: 'SQL filters use SQL-like boolean expressions over message properties; correlation filters match specific property values more efficiently.',
  },
  {
    id: 'con-051', topicId: 'service-bus', difficulty: 'medium',
    question: 'Which receive mode is fastest but risks losing a message if processing fails after receipt?',
    options: ['Peek-Lock', 'Receive-and-Delete', 'Session receive', 'Deferred receive'],
    correctAnswer: 1,
    explanation: 'Receive-and-Delete removes the message on receipt (at-most-once); if processing then fails, the message is lost.',
  },

  // ── Queue Storage ───────────────────────────────────────────────
  {
    id: 'con-052', topicId: 'queue-storage', difficulty: 'easy',
    question: 'What is the maximum size of a single Azure Queue Storage message?',
    options: ['64 KB', '256 KB', '1 MB', '64 MB'],
    correctAnswer: 0,
    explanation: 'Azure Queue Storage messages are up to 64 KB. For larger payloads, store data elsewhere (e.g., Blob) and queue a reference.',
  },
  {
    id: 'con-053', topicId: 'queue-storage', difficulty: 'medium',
    question: 'When a consumer reads a Queue Storage message, what makes it temporarily hidden from other consumers?',
    options: ['Dead-lettering', 'Visibility timeout', 'TTL', 'Session lock'],
    correctAnswer: 1,
    explanation: 'Reading a message makes it invisible for the visibility timeout; if not deleted within that window, it reappears for reprocessing.',
  },
  {
    id: 'con-054', topicId: 'queue-storage', difficulty: 'medium',
    question: 'After successfully processing a Queue Storage message, what must the consumer do?',
    options: ['Nothing', 'Delete the message explicitly', 'Abandon it', 'Dead-letter it'],
    correctAnswer: 1,
    explanation: 'The consumer must explicitly delete the message after processing; otherwise it reappears when the visibility timeout expires.',
  },
  {
    id: 'con-055', topicId: 'queue-storage', difficulty: 'hard',
    question: 'Queue Storage has no native dead-letter queue. How do you handle poison messages?',
    options: ['Ignore them', 'Track DequeueCount and move messages aside after N attempts', 'Use sessions', 'Use Event Grid'],
    correctAnswer: 1,
    explanation: 'Check the message DequeueCount; after a threshold, move the message to a separate poison queue/store, since there is no built-in DLQ.',
  },
  {
    id: 'con-056', topicId: 'queue-storage', difficulty: 'medium',
    question: 'Which is a key limitation of Queue Storage compared to Service Bus queues?',
    options: ['No durability', 'No built-in ordering, sessions, transactions, or topics', 'Cannot scale', 'No encryption'],
    correctAnswer: 1,
    explanation: 'Queue Storage is simple and massively scalable but lacks ordering guarantees, sessions, transactions, duplicate detection, and topics.',
  },
  {
    id: 'con-057', topicId: 'queue-storage', difficulty: 'hard',
    scenario: 'You need ordered processing, transactions, and topic-based pub/sub for enterprise messages.',
    question: 'Which service should you choose over Queue Storage?',
    options: ['Event Grid', 'Azure Service Bus', 'Event Hubs', 'Redis'],
    correctAnswer: 1,
    explanation: 'Service Bus provides ordering (sessions), transactions, duplicate detection, and topics/subscriptions that Queue Storage lacks.',
  },
  {
    id: 'con-058', topicId: 'queue-storage', difficulty: 'medium',
    question: 'Which trigger lets an Azure Function automatically process Queue Storage messages?',
    options: ['Timer trigger', 'Queue trigger', 'Blob trigger', 'HTTP trigger'],
    correctAnswer: 1,
    explanation: 'The Queue Storage trigger invokes a function for each message and, on success, deletes it (with built-in poison-message handling after 5 attempts by default).',
  },
  {
    id: 'con-059', topicId: 'queue-storage', difficulty: 'hard',
    question: 'With the Azure Functions Queue trigger, what happens to a message that repeatedly fails processing?',
    options: ['It is lost immediately', 'After max dequeue attempts (default 5), it is moved to a poison queue', 'It loops forever', 'It is encrypted'],
    correctAnswer: 1,
    explanation: 'The Functions runtime retries a failing queue message and, after the configured max attempts (default 5), moves it to a {queue}-poison queue.',
  },

  // ── Mixed scenarios across integration ──────────────────────────
  {
    id: 'con-060', topicId: 'messaging-choice', difficulty: 'hard',
    scenario: 'A logistics app streams GPS pings from 100,000 trucks for real-time analytics and later batch processing.',
    question: 'Which service should ingest the stream?',
    options: ['Service Bus queue', 'Event Hubs (with Capture for batch)', 'Queue Storage', 'Event Grid'],
    correctAnswer: 1,
    explanation: 'Event Hubs handles high-volume streaming; Capture archives to storage for later batch processing — exactly this scenario.',
  },
  {
    id: 'con-061', topicId: 'messaging-choice', difficulty: 'medium',
    scenario: 'An order service must guarantee each order is processed exactly once, in order, with retries and a dead-letter path.',
    question: 'Which service is the best fit?',
    options: ['Event Hubs', 'Service Bus (sessions + DLQ + duplicate detection)', 'Queue Storage', 'Event Grid'],
    correctAnswer: 1,
    explanation: 'Service Bus provides ordering via sessions, duplicate detection, and a dead-letter queue — ideal for reliable ordered order processing.',
  },
  {
    id: 'con-062', topicId: 'apim', difficulty: 'medium',
    question: 'Which APIM policy section runs after the backend responds, before returning to the caller?',
    options: ['inbound', 'backend', 'outbound', 'on-error'],
    correctAnswer: 2,
    explanation: 'The outbound section processes the response from the backend (e.g., transform body, set headers) before sending it to the client.',
  },
  {
    id: 'con-063', topicId: 'apim', difficulty: 'hard',
    question: 'Which APIM policy section executes when an error occurs in any other section?',
    options: ['inbound', 'backend', 'outbound', 'on-error'],
    correctAnswer: 3,
    explanation: 'The on-error section runs when a policy in any stage throws, letting you customize error responses and logging.',
  },
  {
    id: 'con-064', topicId: 'event-grid', difficulty: 'medium',
    scenario: 'When a new image is uploaded to Blob Storage, a function must create a thumbnail with minimal latency.',
    question: 'Which integration is recommended?',
    options: ['Poll the container on a timer', 'Use the Blob Storage system topic in Event Grid to trigger the function', 'Use Service Bus sessions', 'Use Queue Storage only'],
    correctAnswer: 1,
    explanation: 'Event Grid\'s Blob Created system event triggers the function near-instantly, far better than polling.',
  },
  {
    id: 'con-065', topicId: 'service-bus', difficulty: 'medium',
    question: 'Which property uniquely identifies a message for duplicate detection in Service Bus?',
    options: ['SessionId', 'MessageId', 'PartitionKey', 'CorrelationId'],
    correctAnswer: 1,
    explanation: 'Duplicate detection compares the MessageId within the configured detection window to discard repeats.',
  },
  {
    id: 'con-066', topicId: 'service-bus', difficulty: 'hard',
    question: 'You must process all messages for a given customer strictly in order. What should you set on the messages?',
    options: ['A unique MessageId per message', 'The same SessionId for that customer', 'A short TTL', 'Receive-and-Delete mode'],
    correctAnswer: 1,
    explanation: 'Assigning the same SessionId groups the customer\'s messages into a session that is processed in FIFO order by a single consumer.',
  },
  {
    id: 'con-067', topicId: 'event-hubs', difficulty: 'medium',
    question: 'Which is a recommended checkpoint store for the Event Hubs EventProcessorClient?',
    options: ['A SQL trigger', 'Azure Blob Storage', 'A Key Vault secret', 'A Service Bus topic'],
    correctAnswer: 1,
    explanation: 'The EventProcessorClient typically uses an Azure Blob Storage container as its checkpoint/lease store for coordination.',
  },
  {
    id: 'con-068', topicId: 'apim', difficulty: 'medium',
    question: 'How does APIM commonly authenticate consumer requests at the simplest level?',
    options: ['By IP only', 'Subscription key in a header (Ocp-Apim-Subscription-Key) or query string', 'By blob metadata', 'By TTL'],
    correctAnswer: 1,
    explanation: 'Consumers pass a subscription key (default header Ocp-Apim-Subscription-Key) to be authorized for a product\'s APIs.',
  },
  {
    id: 'con-069', topicId: 'apim', difficulty: 'hard',
    question: 'You want APIM to enforce a maximum of 10 calls per minute per subscription. Which policy and key do you use?',
    options: ['rate-limit-by-key with counter-key based on subscription id', 'ip-filter', 'mock-response', 'set-header'],
    correctAnswer: 0,
    explanation: 'rate-limit-by-key with a counter-key like context.Subscription.Id throttles per subscription over the renewal period.',
  },
  {
    id: 'con-070', topicId: 'event-grid', difficulty: 'medium',
    question: 'Which advanced Event Grid capability lets subscribers filter on values deep within the event data?',
    options: ['Subject filtering only', 'Advanced filters on event fields', 'TTL', 'Sessions'],
    correctAnswer: 1,
    explanation: 'Advanced filters evaluate conditions on specific event fields (e.g., data.key) to deliver only matching events.',
  },
  {
    id: 'con-071', topicId: 'messaging-choice', difficulty: 'medium',
    question: 'Which service is a poor choice for high-frequency telemetry ingestion at millions of events per second?',
    options: ['Event Hubs', 'Service Bus queue', 'Event Hubs with Kafka endpoint', 'Event Hubs Capture'],
    correctAnswer: 1,
    explanation: 'Service Bus is optimized for enterprise messaging, not massive telemetry throughput; Event Hubs is the right choice for that scale.',
  },
  {
    id: 'con-072', topicId: 'service-bus', difficulty: 'medium',
    question: 'What is auto-forwarding in Service Bus?',
    options: ['Automatically deleting messages', 'Chaining a queue/subscription to forward messages to another entity', 'Encrypting messages', 'Scaling partitions'],
    correctAnswer: 1,
    explanation: 'Auto-forwarding automatically moves messages from a queue or subscription to a target queue/topic, enabling fan-in/chaining topologies.',
  },
  {
    id: 'con-073', topicId: 'service-bus', difficulty: 'hard',
    question: 'Which feature lets you set aside a received message to process later without blocking the queue?',
    options: ['Deferral', 'Duplicate detection', 'Capture', 'Checkpointing'],
    correctAnswer: 0,
    explanation: 'Message deferral sets a message aside (retrievable later by sequence number) so you can process other messages first.',
  },
  {
    id: 'con-074', topicId: 'event-hubs', difficulty: 'medium',
    question: 'Which statement about Event Hubs partitions and consumers is correct?',
    options: ['Many consumers in one group can actively read the same partition simultaneously for load balancing', 'Within a consumer group, typically one active reader owns a partition at a time', 'Partitions cannot be read in parallel', 'Consumer groups share offsets'],
    correctAnswer: 1,
    explanation: 'For balanced processing, each partition is typically owned by one active reader within a consumer group; other groups read independently.',
  },
  {
    id: 'con-075', topicId: 'apim', difficulty: 'medium',
    question: 'How can you import an existing API into APIM quickly?',
    options: ['Only manually', 'Import an OpenAPI (Swagger) definition', 'Only via a SAS', 'Only via Event Grid'],
    correctAnswer: 1,
    explanation: 'APIM can import APIs from OpenAPI/Swagger, WSDL, OData, or Azure resources, generating operations automatically.',
  },
  {
    id: 'con-076', topicId: 'queue-storage', difficulty: 'medium',
    question: 'For decoupling a web front-end from a slow background worker cheaply at large scale, which is appropriate?',
    options: ['Event Hubs', 'Queue Storage', 'Event Grid system topic', 'APIM'],
    correctAnswer: 1,
    explanation: 'Queue Storage cheaply decouples producers from background workers at high scale when advanced messaging features are not required.',
  },
  {
    id: 'con-077', topicId: 'event-grid', difficulty: 'hard',
    question: 'Which is true about Event Grid pricing/operation model?',
    options: ['You pay for idle capacity', 'It is serverless and you pay per operation (event)', 'It requires provisioning throughput units', 'It needs a dedicated VM'],
    correctAnswer: 1,
    explanation: 'Event Grid is serverless and billed per operation (events published/delivered), with no capacity to provision.',
  },
  {
    id: 'con-078', topicId: 'service-bus', difficulty: 'medium',
    question: 'Which namespace-level entity contains queues and topics in Service Bus?',
    options: ['A partition', 'A namespace', 'A consumer group', 'A subscription'],
    correctAnswer: 1,
    explanation: 'A Service Bus namespace is the container for messaging entities such as queues and topics.',
  },
  {
    id: 'con-079', topicId: 'event-hubs', difficulty: 'hard',
    question: 'After you create an Event Hub, can you decrease the number of partitions?',
    options: ['Yes, anytime', 'No, partition count is fixed at creation (for standard) and cannot be reduced', 'Only via a SAS', 'Only in Basic tier'],
    correctAnswer: 1,
    explanation: 'Partition count is set at creation and cannot be decreased (and generally not changed for standard), so plan it based on expected throughput.',
  },
  {
    id: 'con-080', topicId: 'apim', difficulty: 'medium',
    question: 'Which APIM concept groups one or more APIs together with access rules and visibility?',
    options: ['Operation', 'Product', 'Backend', 'Gateway'],
    correctAnswer: 1,
    explanation: 'A product bundles APIs, defines terms/limits, and is associated with subscriptions that grant access.',
  },
  {
    id: 'con-081', topicId: 'messaging-choice', difficulty: 'hard',
    scenario: 'You need at-least-once processing of work items, each up to 200 KB, with competing consumers and a dead-letter path.',
    question: 'Which service fits, given the message size?',
    options: ['Queue Storage (64 KB limit)', 'Service Bus (supports larger messages and DLQ)', 'Event Grid', 'Redis'],
    correctAnswer: 1,
    explanation: 'Queue Storage caps at 64 KB; Service Bus supports larger messages (256 KB Standard, up to 100 MB Premium) plus DLQ and competing consumers.',
  },
  {
    id: 'con-082', topicId: 'event-grid', difficulty: 'medium',
    question: 'Which handler would you use to durably buffer Event Grid events for later pull-based processing?',
    options: ['A webhook only', 'Service Bus queue or Storage Queue as the event handler', 'A Key Vault', 'A Redis channel'],
    correctAnswer: 1,
    explanation: 'Routing Event Grid events to a Service Bus or Storage Queue lets consumers pull and process them durably at their own pace.',
  },
  {
    id: 'con-083', topicId: 'service-bus', difficulty: 'medium',
    question: 'What does PrefetchCount do in a Service Bus receiver?',
    options: ['Encrypts messages', 'Retrieves additional messages into a local cache to improve throughput', 'Deletes messages', 'Creates partitions'],
    correctAnswer: 1,
    explanation: 'Prefetch fetches extra messages ahead of time into a local buffer, reducing round-trips and improving throughput (at the cost of lock duration risk).',
  },
  {
    id: 'con-084', topicId: 'apim', difficulty: 'hard',
    question: 'You need APIM to transform a backend XML response into JSON for clients. Which policy helps?',
    options: ['xml-to-json', 'validate-jwt', 'rate-limit', 'ip-filter'],
    correctAnswer: 0,
    explanation: 'The xml-to-json policy (in outbound) converts XML responses to JSON, and json-to-xml does the reverse.',
  },
  {
    id: 'con-085', topicId: 'event-hubs', difficulty: 'medium',
    question: 'Which best describes the relationship between throughput units and partitions in standard Event Hubs?',
    options: ['They are the same thing', 'TUs control aggregate capacity; partitions enable parallelism and ordering', 'Partitions set billing', 'TUs guarantee ordering'],
    correctAnswer: 1,
    explanation: 'TUs cap total ingress/egress; partitions provide parallel, ordered streams. You scale TUs for throughput and choose partitions for parallelism.',
  },
  {
    id: 'con-086', topicId: 'service-bus', difficulty: 'medium',
    question: 'Which receive approach should you use to reliably ensure a message is only removed after successful processing?',
    options: ['Receive-and-Delete', 'Peek-Lock then Complete', 'Fire and forget', 'Auto-delete'],
    correctAnswer: 1,
    explanation: 'Peek-Lock locks the message; calling Complete only after successful processing guarantees the message is not lost on failure.',
  },
  {
    id: 'con-087', topicId: 'queue-storage', difficulty: 'medium',
    question: 'Which storage service component hosts Queue Storage?',
    options: ['A dedicated Service Bus namespace', 'An Azure Storage account', 'An Event Hubs namespace', 'A Key Vault'],
    correctAnswer: 1,
    explanation: 'Queue Storage is part of an Azure Storage account, alongside Blob, Table, and File services.',
  },
  {
    id: 'con-088', topicId: 'apim', difficulty: 'medium',
    question: 'Which APIM feature lets you protect backends by terminating client connections and forwarding only validated calls?',
    options: ['The gateway acting as a facade/reverse proxy', 'A SAS token', 'A storage queue', 'A consumer group'],
    correctAnswer: 0,
    explanation: 'The APIM gateway is a managed facade/reverse proxy that fronts backends, applying security and policies before forwarding requests.',
  },
  {
    id: 'con-089', topicId: 'event-grid', difficulty: 'hard',
    question: 'Which is NOT a valid Event Grid topic type?',
    options: ['System topic', 'Custom topic', 'Partner topic', 'Consumer topic'],
    correctAnswer: 3,
    explanation: 'Event Grid has system, custom, and partner topics. "Consumer topic" is not an Event Grid concept.',
  },
  {
    id: 'con-090', topicId: 'service-bus', difficulty: 'hard',
    scenario: 'A topic has subscriptions for "audit" (all messages) and "highValue" (orders over $1000).',
    question: 'How do you configure the highValue subscription?',
    options: ['Use a SQL filter like amount > 1000', 'Use sessions', 'Use duplicate detection', 'Use Receive-and-Delete'],
    correctAnswer: 0,
    explanation: 'A SQL filter (e.g., amount > 1000) on the subscription ensures it only receives messages whose properties match the condition.',
  },
  {
    id: 'con-091', topicId: 'messaging-choice', difficulty: 'medium',
    question: 'Which pairing of "intent" to service is correct?',
    options: ['Stream telemetry → Service Bus', 'React to discrete events → Event Grid', 'Enterprise transactional messaging → Event Hubs', 'Simple cheap queue → Event Grid'],
    correctAnswer: 1,
    explanation: 'Event Grid is for reacting to discrete events. Telemetry streaming → Event Hubs; transactional messaging → Service Bus; simple queue → Queue Storage.',
  },
  {
    id: 'con-092', topicId: 'apim', difficulty: 'medium',
    question: 'How can APIM expose a single facade over multiple microservice backends?',
    options: ['It cannot', 'Define APIs/operations that route to different backend services via set-backend-service', 'Only one backend is allowed', 'Use a SAS'],
    correctAnswer: 1,
    explanation: 'APIM can route different operations to different backends (e.g., with set-backend-service), presenting a unified API facade.',
  },
  {
    id: 'con-093', topicId: 'event-hubs', difficulty: 'medium',
    question: 'What is the default minimum number of partitions you should consider for parallel consumers?',
    options: ['Fewer partitions than consumers', 'At least as many partitions as the maximum number of concurrent consumers you need', 'Always one', 'Partitions do not affect consumers'],
    correctAnswer: 1,
    explanation: 'Because a partition is typically processed by one consumer per group, you need at least as many partitions as concurrent consumers for parallelism.',
  },
  {
    id: 'con-094', topicId: 'queue-storage', difficulty: 'hard',
    question: 'How can you extend processing time for a Queue Storage message beyond the original visibility timeout?',
    options: ['You cannot', 'Update the message with a new visibility timeout (UpdateMessage)', 'Delete and recreate it', 'Use sessions'],
    correctAnswer: 1,
    explanation: 'Calling UpdateMessage lets you extend the visibility timeout (and optionally change content) while still processing.',
  },
  {
    id: 'con-095', topicId: 'service-bus', difficulty: 'medium',
    question: 'Which is true about Service Bus topics versus queues?',
    options: ['Queues support multiple independent subscribers; topics are point-to-point', 'Topics support multiple subscriptions (pub/sub); queues are point-to-point', 'They are identical', 'Topics cannot filter'],
    correctAnswer: 1,
    explanation: 'Queues are point-to-point (one logical consumer set competing); topics enable pub/sub where each subscription gets its own filtered copy.',
  },
  {
    id: 'con-096', topicId: 'apim', difficulty: 'hard',
    question: 'Which APIM authentication option is recommended over storing backend credentials in policies?',
    options: ['Hard-coded basic auth', 'Managed identity (authentication-managed-identity) or named values referencing Key Vault', 'A SAS in the URL', 'No authentication'],
    correctAnswer: 1,
    explanation: 'Use managed identity to authenticate to backends, and store secrets as named values backed by Key Vault rather than in plain policies.',
  },
  {
    id: 'con-097', topicId: 'event-grid', difficulty: 'medium',
    question: 'Which Azure service can act as both an Event Grid event source AND be triggered by Event Grid?',
    options: ['Key Vault', 'Blob Storage', 'Both can integrate with Event Grid as sources, with handlers like Functions reacting', 'Neither'],
    correctAnswer: 2,
    explanation: 'Services like Blob Storage and Key Vault publish events to Event Grid (sources), and handlers such as Functions react to them.',
  },
  {
    id: 'con-098', topicId: 'service-bus', difficulty: 'medium',
    question: 'What is the effect of a message exceeding its time-to-live (TTL) in Service Bus?',
    options: ['It is processed faster', 'It expires and is moved to the dead-letter queue (if enabled) or dropped', 'It is duplicated', 'It is encrypted'],
    correctAnswer: 1,
    explanation: 'Expired messages are dead-lettered (when dead-lettering on expiration is enabled) or removed, preventing stale processing.',
  },
  {
    id: 'con-099', topicId: 'event-hubs', difficulty: 'hard',
    question: 'Which tier of Event Hubs offers Processing Units and isolation for predictable high-end performance?',
    options: ['Basic', 'Standard', 'Premium/Dedicated', 'Free'],
    correctAnswer: 2,
    explanation: 'Event Hubs Premium (and Dedicated) provide isolated capacity measured in Processing Units/Capacity Units for predictable high throughput.',
  },
  {
    id: 'con-100', topicId: 'apim', difficulty: 'medium',
    question: 'Which named construct in APIM securely stores reusable values (including Key Vault secrets) for use in policies?',
    options: ['Products', 'Named values', 'Operations', 'Subscriptions'],
    correctAnswer: 1,
    explanation: 'Named values are reusable key/value pairs (optionally secret or Key Vault-backed) referenced from policies, avoiding hard-coded secrets.',
  },
  {
    id: 'con-101', topicId: 'messaging-choice', difficulty: 'medium',
    question: 'Which service should you use to broadcast a single event to potentially many, dynamically changing subscribers with filtering?',
    options: ['Queue Storage', 'Event Grid', 'A single Service Bus queue', 'Redis'],
    correctAnswer: 1,
    explanation: 'Event Grid is purpose-built for broadcasting discrete events to many subscribers with per-subscription filtering.',
  },
  {
    id: 'con-102', topicId: 'service-bus', difficulty: 'hard',
    question: 'To process a Service Bus session, what must the receiver do?',
    options: ['Receive normally', 'Accept the session (AcceptNextSessionAsync / session receiver) to lock and process its messages in order', 'Use Receive-and-Delete', 'Use Event Grid'],
    correctAnswer: 1,
    explanation: 'A session-aware receiver accepts a session, locking all its messages so they are processed in FIFO order by that single receiver.',
  },
  {
    id: 'con-103', topicId: 'apim', difficulty: 'medium',
    question: 'Which observability integration does APIM support for request analytics and logs?',
    options: ['Only email', 'Azure Monitor and Application Insights', 'Only blob logs', 'None'],
    correctAnswer: 1,
    explanation: 'APIM integrates with Azure Monitor metrics/logs and Application Insights for request analytics, tracing, and diagnostics.',
  },
  {
    id: 'con-104', topicId: 'event-grid', difficulty: 'medium',
    question: 'What is the recommended way to secure a webhook handler subscribed to Event Grid?',
    options: ['No security needed', 'Validate the subscription handshake and use authentication (e.g., validation + AAD/secret)', 'Open all ports', 'Use a SAS in the body'],
    correctAnswer: 1,
    explanation: 'Webhook handlers should complete the validation handshake and enforce authentication so only Event Grid can post events.',
  },
  {
    id: 'con-105', topicId: 'event-hubs', difficulty: 'medium',
    question: 'Which is the best description of an Event Hubs "offset"?',
    options: ['A security token', 'A position marker of an event within a partition', 'A partition key', 'A consumer group name'],
    correctAnswer: 1,
    explanation: 'An offset marks the byte/sequence position of an event in a partition; consumers checkpoint offsets to track progress.',
  },
  {
    id: 'con-106', topicId: 'queue-storage', difficulty: 'medium',
    question: 'What is a recommended pattern when a queued task references data larger than 64 KB?',
    options: ['Split into many messages', 'Store the payload in Blob storage and put a reference (claim check) in the queue', 'Use Event Grid', 'Compress to fit always'],
    correctAnswer: 1,
    explanation: 'The claim-check pattern stores large payloads in Blob storage and enqueues only a reference, staying within the 64 KB message limit.',
  },
  {
    id: 'con-107', topicId: 'service-bus', difficulty: 'medium',
    question: 'Which Service Bus capability supports grouping operations so they all succeed or fail together?',
    options: ['Transactions', 'Sessions', 'Capture', 'Checkpointing'],
    correctAnswer: 0,
    explanation: 'Service Bus supports transactions, allowing multiple messaging operations to be committed or rolled back atomically.',
  },
  {
    id: 'con-108', topicId: 'apim', difficulty: 'hard',
    scenario: 'You must protect a backend from spikes, validate caller tokens, and cache GET responses for 60 seconds.',
    question: 'Which combination of inbound/outbound policies achieves this?',
    options: ['rate-limit + validate-jwt (inbound) and cache-lookup/cache-store (60s)', 'mock-response only', 'ip-filter only', 'set-header only'],
    correctAnswer: 0,
    explanation: 'rate-limit throttles spikes, validate-jwt authorizes callers, and cache-lookup/cache-store with a 60s duration cache GET responses.',
  },
  {
    id: 'con-109', topicId: 'messaging-choice', difficulty: 'hard',
    question: 'Which statement correctly contrasts Event Hubs and Service Bus?',
    options: ['Both are for high-volume streaming', 'Event Hubs is partition-based streaming with consumer-managed offsets; Service Bus is a broker with per-message delivery state', 'Service Bus uses partitions and offsets', 'Event Hubs has dead-letter sessions'],
    correctAnswer: 1,
    explanation: 'Event Hubs streams events across partitions with consumers tracking offsets; Service Bus is a broker tracking per-message state (locks, delivery count, DLQ).',
  },
  {
    id: 'con-110', topicId: 'event-grid', difficulty: 'medium',
    question: 'Which delivery feature helps Event Grid avoid overwhelming a slow subscriber?',
    options: ['Sessions', 'Retry with exponential back-off (and eventual dead-letter)', 'Partitions', 'Throughput units'],
    correctAnswer: 1,
    explanation: 'Event Grid retries failed deliveries with exponential back-off and can dead-letter after the TTL, accommodating temporarily slow/unavailable subscribers.',
  },
]

export const connectQuestions = buildQuestions('connect-consume', 'Connect to and consume Azure services and third-party services', seeds)
