import { buildQuestions, QSeed } from './_builder'

const seeds: QSeed[] = [
  // ── Application Insights ────────────────────────────────────────
  {
    id: 'mon-001', topicId: 'app-insights', difficulty: 'easy',
    question: 'Application Insights is a feature of which Azure service?',
    options: ['Azure Storage', 'Azure Monitor', 'Azure Key Vault', 'Azure DevOps'],
    correctAnswer: 1,
    explanation: 'Application Insights is the application performance monitoring (APM) capability within Azure Monitor.',
  },
  {
    id: 'mon-002', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which value should a modern app use to send telemetry to Application Insights?',
    options: ['Instrumentation key only', 'Connection string', 'A SAS token', 'The resource group name'],
    correctAnswer: 1,
    explanation: 'Use the Application Insights connection string; the standalone instrumentation key is deprecated.',
  },
  {
    id: 'mon-003', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which method records a custom business event in Application Insights?',
    options: ['TrackException', 'TrackEvent', 'TrackDependency', 'TrackRequest'],
    correctAnswer: 1,
    explanation: 'TrackEvent records custom events (e.g., "OrderPlaced"). TrackException logs errors; TrackDependency logs outbound calls.',
  },
  {
    id: 'mon-004', topicId: 'app-insights', difficulty: 'hard',
    question: 'To reduce telemetry volume and cost while keeping statistically representative data, what should you configure?',
    options: ['Disable logging', 'Sampling (e.g., adaptive sampling)', 'A bigger App Service plan', 'More instrumentation keys'],
    correctAnswer: 1,
    explanation: 'Sampling reduces the amount of telemetry sent/stored while preserving representative data. Adaptive sampling is the ASP.NET default.',
  },
  {
    id: 'mon-005', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which Application Insights feature visualizes components and their dependencies with health status?',
    options: ['Live Metrics', 'Application Map', 'Funnels', 'Workbooks'],
    correctAnswer: 1,
    explanation: 'Application Map shows the topology of components and dependencies with performance/failure indicators for distributed apps.',
  },
  {
    id: 'mon-006', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which method tracks the duration and success of an outbound call to a database or external API?',
    options: ['TrackTrace', 'TrackDependency', 'TrackEvent', 'TrackMetric'],
    correctAnswer: 1,
    explanation: 'TrackDependency records calls to external dependencies (SQL, HTTP, etc.), including duration and success, feeding the Application Map.',
  },
  {
    id: 'mon-007', topicId: 'app-insights', difficulty: 'hard',
    question: 'Which sampling type discards telemetry at the SDK before it is sent, reducing both network and ingestion?',
    options: ['Ingestion sampling', 'Adaptive/fixed-rate sampling (client-side)', 'No sampling', 'Log Analytics sampling'],
    correctAnswer: 1,
    explanation: 'Adaptive and fixed-rate sampling run in the SDK (client side), reducing data before transmission. Ingestion sampling happens at the service.',
  },
  {
    id: 'mon-008', topicId: 'app-insights', difficulty: 'medium',
    question: 'What correlates telemetry across services so you can follow one request end-to-end?',
    options: ['A SAS token', 'Distributed tracing with an operation/correlation ID', 'Sampling', 'A feature flag'],
    correctAnswer: 1,
    explanation: 'Distributed tracing propagates a correlation/operation ID across services so Application Insights can stitch a single transaction together.',
  },
  {
    id: 'mon-009', topicId: 'app-insights', difficulty: 'easy',
    question: 'Which method logs a handled exception to Application Insights?',
    options: ['TrackEvent', 'TrackException', 'TrackMetric', 'TrackRequest'],
    correctAnswer: 1,
    explanation: 'TrackException sends exception telemetry (stack trace, properties) for diagnostics.',
  },
  {
    id: 'mon-010', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which low-latency view shows incoming requests and performance in near real time (about one second)?',
    options: ['Application Map', 'Live Metrics Stream', 'Workbooks', 'Usage funnels'],
    correctAnswer: 1,
    explanation: 'Live Metrics Stream shows telemetry with ~1 second latency and is not subject to sampling, ideal during deployments.',
  },
  {
    id: 'mon-011', topicId: 'app-insights', difficulty: 'hard',
    question: 'You want to enable monitoring on an App Service without changing application code. What can you use?',
    options: ['Manual SDK only', 'Auto-instrumentation (codeless attach)', 'A SAS token', 'A feature flag'],
    correctAnswer: 1,
    explanation: 'Auto-instrumentation (codeless) attaches the Application Insights agent to collect telemetry without modifying app code.',
  },
  {
    id: 'mon-012', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which method records a custom numeric metric such as queue length?',
    options: ['TrackMetric', 'TrackTrace', 'TrackEvent', 'TrackException'],
    correctAnswer: 0,
    explanation: 'TrackMetric records custom numeric measurements that can be aggregated and charted.',
  },

  // ── Availability tests & alerts ─────────────────────────────────
  {
    id: 'mon-013', topicId: 'availability-alerts', difficulty: 'medium',
    question: 'What does an Application Insights availability test do?',
    options: ['Encrypts data', 'Periodically probes your endpoint from multiple regions to measure uptime', 'Scales your app', 'Stores secrets'],
    correctAnswer: 1,
    explanation: 'Availability tests send synthetic requests from multiple Azure regions to verify your app is reachable and responsive.',
  },
  {
    id: 'mon-014', topicId: 'availability-alerts', difficulty: 'hard',
    question: 'To avoid false alarms from a single failing region, how should you configure availability alerting?',
    options: ['Alert on any single region failure', 'Alert when a threshold number of locations fail (X of Y)', 'Disable alerts', 'Only test from one region'],
    correctAnswer: 1,
    explanation: 'Configuring an alert to fire only when X of Y test locations fail reduces false positives from transient single-region issues.',
  },
  {
    id: 'mon-015', topicId: 'availability-alerts', difficulty: 'medium',
    question: 'Which mechanism delivers alert notifications to email, SMS, webhooks, or a Logic App?',
    options: ['A SAS token', 'An action group', 'A deployment slot', 'A feature flag'],
    correctAnswer: 1,
    explanation: 'Action groups define the actions/notifications (email, SMS, webhook, Logic App, Function, etc.) executed when an alert fires.',
  },
  {
    id: 'mon-016', topicId: 'availability-alerts', difficulty: 'medium',
    question: 'For a complex multi-step availability check, which approach should you use?',
    options: ['Standard URL ping test', 'Custom TrackAvailability() telemetry from code', 'A blob trigger', 'A SAS token'],
    correctAnswer: 1,
    explanation: 'For multi-step or custom logic, emit availability results from code using TrackAvailability(), which surfaces in Application Insights.',
  },
  {
    id: 'mon-017', topicId: 'availability-alerts', difficulty: 'medium',
    question: 'An alert rule fundamentally consists of which two parts?',
    options: ['A secret and a key', 'A condition (signal + threshold) and an action group', 'A blob and a queue', 'A slot and a swap'],
    correctAnswer: 1,
    explanation: 'An alert rule combines a condition (the signal and threshold to evaluate) with one or more action groups to run when it triggers.',
  },
  {
    id: 'mon-018', topicId: 'availability-alerts', difficulty: 'hard',
    question: 'You want to be alerted when server response time exceeds 2 seconds averaged over 5 minutes. What type of signal is this?',
    options: ['Log-based custom query alert or a metric alert on response time', 'Availability test only', 'A feature flag', 'A SAS expiry'],
    correctAnswer: 0,
    explanation: 'Response time can be alerted via a metric alert or a log (KQL) alert evaluating the average over the window.',
  },

  // ── Redis cache ─────────────────────────────────────────────────
  {
    id: 'mon-019', topicId: 'redis-cache', difficulty: 'easy',
    question: 'What is the primary purpose of Azure Cache for Redis?',
    options: ['Persistent relational storage', 'Low-latency in-memory caching and session/state storage', 'Container orchestration', 'Secret storage'],
    correctAnswer: 1,
    explanation: 'Azure Cache for Redis provides fast in-memory caching, session state, and pub/sub messaging to reduce backend load and latency.',
  },
  {
    id: 'mon-020', topicId: 'redis-cache', difficulty: 'medium',
    question: 'In the cache-aside pattern, what happens on a cache miss?',
    options: ['The request fails', 'The app loads from the database, returns it, and populates the cache with a TTL', 'The cache is cleared', 'The app retries forever'],
    correctAnswer: 1,
    explanation: 'Cache-aside (lazy loading): on a miss the app reads from the data store, returns the value, and writes it to the cache with an expiration.',
  },
  {
    id: 'mon-021', topicId: 'redis-cache', difficulty: 'medium',
    question: 'Why should cached items have a TTL (expiration)?',
    options: ['To increase latency', 'To avoid stale data and unbounded memory growth', 'To disable the cache', 'To enable HTTPS'],
    correctAnswer: 1,
    explanation: 'Setting a TTL ensures stale data is eventually refreshed and prevents the cache from growing without bound.',
  },
  {
    id: 'mon-022', topicId: 'redis-cache', difficulty: 'hard',
    question: 'Which Azure Cache for Redis tier is required for clustering, data persistence, and VNet injection?',
    options: ['Basic', 'Standard', 'Premium', 'There is no such tier'],
    correctAnswer: 2,
    explanation: 'The Premium tier adds clustering (scale-out), data persistence (RDB/AOF), and VNet injection; Basic/Standard do not.',
  },
  {
    id: 'mon-023', topicId: 'redis-cache', difficulty: 'medium',
    question: 'Which Redis eviction policy removes the least recently used keys among those with a TTL when memory is full?',
    options: ['noeviction', 'volatile-lru', 'allkeys-random', 'volatile-ttl'],
    correctAnswer: 1,
    explanation: 'volatile-lru evicts least-recently-used keys but only among keys that have an expiration set.',
  },
  {
    id: 'mon-024', topicId: 'redis-cache', difficulty: 'hard',
    question: 'Which eviction policy causes write commands to fail when memory is full instead of evicting keys?',
    options: ['allkeys-lru', 'noeviction', 'volatile-lfu', 'allkeys-random'],
    correctAnswer: 1,
    explanation: 'noeviction returns errors on writes when maxmemory is reached rather than removing any keys.',
  },
  {
    id: 'mon-025', topicId: 'redis-cache', difficulty: 'medium',
    question: 'Which caching pattern keeps the cache and database consistent by writing to both on each update?',
    options: ['Cache-aside', 'Write-through', 'Read-replica', 'Sharding'],
    correctAnswer: 1,
    explanation: 'Write-through writes to the cache and the database together so reads from the cache stay consistent with the store.',
  },
  {
    id: 'mon-026', topicId: 'redis-cache', difficulty: 'medium',
    question: 'A stateless web farm needs shared session state across instances. How can Redis help?',
    options: ['It cannot', 'Store session state in Redis so any instance can read it', 'Use local memory only', 'Use a SAS token'],
    correctAnswer: 1,
    explanation: 'Storing session state in Redis lets a stateless, scaled-out web tier share sessions across all instances.',
  },
  {
    id: 'mon-027', topicId: 'redis-cache', difficulty: 'hard',
    question: 'Which Redis capability lets you publish messages to subscribers for lightweight real-time messaging?',
    options: ['Pub/Sub', 'TTL', 'Eviction', 'Clustering'],
    correctAnswer: 0,
    explanation: 'Redis Pub/Sub allows publishers to send messages to channels that subscribers receive, useful for real-time notifications.',
  },
  {
    id: 'mon-028', topicId: 'redis-cache', difficulty: 'medium',
    question: 'What is a recommended way to handle transient connection failures to Azure Cache for Redis?',
    options: ['Crash the app', 'Implement retry with exponential backoff using the client library', 'Disable the cache', 'Use a SAS token'],
    correctAnswer: 1,
    explanation: 'Use the client\'s retry/backoff features (e.g., StackExchange.Redis) to gracefully handle transient connectivity issues.',
  },

  // ── KQL / Log Analytics ─────────────────────────────────────────
  {
    id: 'mon-029', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which query language is used to analyze logs in Log Analytics / Application Insights?',
    options: ['SQL', 'KQL (Kusto Query Language)', 'GraphQL', 'XPath'],
    correctAnswer: 1,
    explanation: 'KQL (Kusto Query Language) is used to query logs and traces in Log Analytics and Application Insights.',
  },
  {
    id: 'mon-030', topicId: 'app-insights', difficulty: 'hard',
    question: 'In KQL, which operator filters rows based on a condition?',
    options: ['project', 'where', 'summarize', 'render'],
    correctAnswer: 1,
    explanation: 'The where operator filters rows by a predicate. project selects columns, summarize aggregates, and render visualizes.',
  },
  {
    id: 'mon-031', topicId: 'app-insights', difficulty: 'medium',
    question: 'In KQL, which operator aggregates data (e.g., count by a column)?',
    options: ['where', 'summarize', 'extend', 'sort'],
    correctAnswer: 1,
    explanation: 'summarize performs aggregations such as count(), avg(), and grouping with by clauses.',
  },
  {
    id: 'mon-032', topicId: 'app-insights', difficulty: 'medium',
    question: 'What is the general difference between Azure Monitor metrics and logs?',
    options: ['Metrics are slow; logs are instant', 'Metrics are lightweight numeric values collected at near real-time; logs are richer records with some ingestion latency', 'They are identical', 'Logs cannot be queried'],
    correctAnswer: 1,
    explanation: 'Metrics are numeric, time-series, near real-time and cheap; logs are detailed records queried with KQL and have some ingestion delay.',
  },
  {
    id: 'mon-033', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which destination do Application Insights logs ultimately reside in for KQL querying?',
    options: ['A storage queue', 'A Log Analytics workspace', 'A Key Vault', 'A Service Bus topic'],
    correctAnswer: 1,
    explanation: 'Workspace-based Application Insights stores telemetry in a Log Analytics workspace, where you query it with KQL.',
  },
  {
    id: 'mon-034', topicId: 'app-insights', difficulty: 'hard',
    question: 'You need to add custom properties (key/value) to all telemetry from a component. What should you implement?',
    options: ['A SAS token', 'A telemetry initializer', 'A feature flag', 'An action group'],
    correctAnswer: 1,
    explanation: 'A telemetry initializer modifies/enriches telemetry (e.g., adding global properties) before it is sent.',
  },
  {
    id: 'mon-035', topicId: 'app-insights', difficulty: 'hard',
    question: 'To drop or modify specific telemetry items before sending (e.g., filter health-check requests), what do you implement?',
    options: ['A telemetry processor', 'A SAS policy', 'An eviction policy', 'A deployment slot'],
    correctAnswer: 0,
    explanation: 'A telemetry processor can filter out or alter telemetry items (e.g., exclude noisy ping requests) in the pipeline.',
  },
  {
    id: 'mon-036', topicId: 'redis-cache', difficulty: 'medium',
    question: 'Which client library is commonly used to connect .NET apps to Azure Cache for Redis?',
    options: ['StackExchange.Redis', 'Newtonsoft.Json', 'Polly only', 'Entity Framework'],
    correctAnswer: 0,
    explanation: 'StackExchange.Redis is the widely used .NET client for Redis, including Azure Cache for Redis.',
  },
  {
    id: 'mon-037', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which telemetry type is automatically collected for incoming HTTP requests to a monitored web app?',
    options: ['Request telemetry', 'Custom events only', 'Nothing is automatic', 'Only exceptions'],
    correctAnswer: 0,
    explanation: 'Request telemetry (URL, duration, response code, success) is auto-collected for incoming requests when instrumented.',
  },
  {
    id: 'mon-038', topicId: 'availability-alerts', difficulty: 'medium',
    question: 'Which alert action could automatically remediate an issue (e.g., scale or restart) when triggered?',
    options: ['Email only', 'A webhook/Function/Logic App in the action group', 'A SAS token', 'A feature flag'],
    correctAnswer: 1,
    explanation: 'Action groups can call automation (Logic App, Function, webhook, Automation runbook) to remediate issues automatically.',
  },
  {
    id: 'mon-039', topicId: 'redis-cache', difficulty: 'hard',
    scenario: 'A high-traffic product catalog page reads the same data repeatedly from a SQL database, causing load and latency.',
    question: 'What is the most effective optimization?',
    options: ['Add more SQL replicas only', 'Implement cache-aside with Azure Cache for Redis and a sensible TTL', 'Disable indexing', 'Use a SAS token'],
    correctAnswer: 1,
    explanation: 'Caching frequently read, slowly changing catalog data in Redis (cache-aside with TTL) reduces database load and latency dramatically.',
  },
  {
    id: 'mon-040', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which Application Insights experience helps follow a single failed transaction across components for root-cause analysis?',
    options: ['Transaction search / end-to-end transaction details', 'Sampling', 'Action groups', 'Eviction policies'],
    correctAnswer: 0,
    explanation: 'End-to-end transaction details (transaction search) reconstruct a single operation across components to pinpoint failures.',
  },
  {
    id: 'mon-041', topicId: 'redis-cache', difficulty: 'medium',
    question: 'Which problem can occur if many cached keys expire at the same instant under heavy load?',
    options: ['Cache stampede / thundering herd', 'Data encryption', 'Slot swap', 'Token expiry'],
    correctAnswer: 0,
    explanation: 'A cache stampede happens when many keys expire together and concurrent misses overload the backend; mitigate with jittered TTLs or locks.',
  },
  {
    id: 'mon-042', topicId: 'app-insights', difficulty: 'easy',
    question: 'Which Azure Monitor signal type would you use to chart CPU percentage over time with minimal latency?',
    options: ['Logs', 'Metrics', 'Traces', 'Events'],
    correctAnswer: 1,
    explanation: 'Platform metrics (like CPU%) are numeric time-series collected at near real-time, ideal for charts and metric alerts.',
  },
  {
    id: 'mon-043', topicId: 'availability-alerts', difficulty: 'medium',
    question: 'What is the recommended minimum number of test locations for an availability test to reduce false positives?',
    options: ['One', 'At least five (and alert on multiple failing)', 'Zero', 'Exactly two only'],
    correctAnswer: 1,
    explanation: 'Microsoft recommends testing from at least five locations and alerting when multiple locations fail to avoid noise from transient issues.',
  },
  {
    id: 'mon-044', topicId: 'redis-cache', difficulty: 'hard',
    question: 'Which Premium Redis persistence option logs every write for the most durable recovery?',
    options: ['RDB snapshots', 'AOF (Append Only File)', 'No persistence', 'TTL'],
    correctAnswer: 1,
    explanation: 'AOF persistence records every write operation, giving more durable recovery than periodic RDB snapshots (at higher overhead).',
  },
  {
    id: 'mon-045', topicId: 'app-insights', difficulty: 'medium',
    question: 'Which is the correct order to enable end-to-end monitoring for a new microservice?',
    options: ['Add the SDK/connection string, instrument code/auto-instrument, then build dashboards/alerts', 'Create alerts first, then never add the SDK', 'Only enable sampling', 'Only store logs in Blob'],
    correctAnswer: 0,
    explanation: 'First instrument the service (SDK/connection string or auto-instrumentation), then build queries, dashboards, and alerts on the collected telemetry.',
  },
]

export const monitorQuestions = buildQuestions('monitor-optimize', 'Monitor, troubleshoot, and optimize Azure solutions', seeds)
