import { buildQuestions, QSeed } from './_builder'

const seeds: QSeed[] = [
  // ── Identity platform & OAuth flows ─────────────────────────────
  {
    id: 'sec-001', topicId: 'identity-flows', difficulty: 'medium',
    question: 'A background daemon service with no user must call an API using its own identity. Which OAuth 2.0 flow is correct?',
    options: ['Authorization Code', 'Client Credentials', 'On-Behalf-Of', 'Device Code'],
    correctAnswer: 1,
    explanation: 'The Client Credentials flow is for app-only (no user) scenarios such as daemons/services, authenticating with a secret or certificate.',
  },
  {
    id: 'sec-002', topicId: 'identity-flows', difficulty: 'medium',
    question: 'A web API receives a user token and must call a downstream API as that same user. Which flow applies?',
    options: ['Client Credentials', 'On-Behalf-Of (OBO)', 'Device Code', 'Implicit'],
    correctAnswer: 1,
    explanation: 'The On-Behalf-Of flow lets a middle-tier API exchange the incoming user token for a token to call a downstream API as the user.',
  },
  {
    id: 'sec-003', topicId: 'identity-flows', difficulty: 'easy',
    question: 'Which library does Microsoft recommend for acquiring tokens from the Microsoft identity platform?',
    options: ['ADAL', 'MSAL (Microsoft Authentication Library)', 'OpenSSL', 'JWT.io'],
    correctAnswer: 1,
    explanation: 'MSAL is the current recommended library; ADAL is deprecated. MSAL handles token acquisition, caching, and refresh.',
  },
  {
    id: 'sec-004', topicId: 'identity-flows', difficulty: 'hard',
    question: 'A single-page application (SPA) signs users in interactively. Which flow and enhancement should it use?',
    options: ['Implicit flow without PKCE', 'Authorization Code flow with PKCE', 'Client Credentials', 'Device Code'],
    correctAnswer: 1,
    explanation: 'Modern SPAs use the Authorization Code flow with PKCE (proof key for code exchange) rather than the legacy implicit flow.',
  },
  {
    id: 'sec-005', topicId: 'identity-flows', difficulty: 'medium',
    question: 'What is the difference between an ID token and an access token?',
    options: ['They are identical', 'ID token proves authentication (who the user is); access token authorizes calls to a resource', 'Access token proves identity; ID token authorizes', 'Both are only for refresh'],
    correctAnswer: 1,
    explanation: 'The ID token (OpenID Connect) authenticates the user; the access token (OAuth 2.0) authorizes calls to a protected resource/API.',
  },
  {
    id: 'sec-006', topicId: 'identity-flows', difficulty: 'medium',
    question: 'Which permission type acts on behalf of a signed-in user versus as the application itself?',
    options: ['Delegated permissions vs application permissions', 'Scoped vs global', 'Read vs write only', 'Public vs confidential'],
    correctAnswer: 0,
    explanation: 'Delegated permissions act for a signed-in user; application permissions are app-only (no user) and typically require admin consent.',
  },
  {
    id: 'sec-007', topicId: 'identity-flows', difficulty: 'hard',
    question: 'A CLI tool runs on a device without a browser. Which flow lets the user authenticate on a separate device?',
    options: ['Authorization Code', 'Device Code', 'Client Credentials', 'On-Behalf-Of'],
    correctAnswer: 1,
    explanation: 'The Device Code flow displays a code the user enters on another device with a browser to complete sign-in — ideal for input-constrained devices.',
  },
  {
    id: 'sec-008', topicId: 'identity-flows', difficulty: 'medium',
    question: 'In MSAL, what does AcquireTokenSilent do?',
    options: ['Always prompts the user', 'Retrieves a cached/refreshed token without user interaction when possible', 'Revokes tokens', 'Validates a JWT signature'],
    correctAnswer: 1,
    explanation: 'AcquireTokenSilent returns a token from the cache or uses a refresh token silently; it only requires interaction if silent acquisition fails.',
  },
  {
    id: 'sec-009', topicId: 'identity-flows', difficulty: 'medium',
    question: 'Application permissions in Microsoft Entra ID typically require what before they can be used?',
    options: ['Nothing', 'Admin consent', 'A SAS token', 'A managed identity'],
    correctAnswer: 1,
    explanation: 'Application (app-only) permissions are high-privilege and require tenant admin consent before the app can use them.',
  },

  // ── Managed identities ──────────────────────────────────────────
  {
    id: 'sec-010', topicId: 'managed-identity', difficulty: 'easy',
    question: 'What is the primary benefit of using a managed identity?',
    options: ['Faster compute', 'Authenticating to Azure services without storing credentials in code', 'Cheaper storage', 'Stronger encryption keys'],
    correctAnswer: 1,
    explanation: 'Managed identities let Azure resources authenticate to services (Key Vault, Storage, etc.) without any credentials in code or config.',
  },
  {
    id: 'sec-011', topicId: 'managed-identity', difficulty: 'medium',
    question: 'You need one identity shared across several App Services and a VM. Which managed identity type fits?',
    options: ['System-assigned', 'User-assigned', 'Service principal secret', 'A SAS token'],
    correctAnswer: 1,
    explanation: 'A user-assigned managed identity is a standalone resource that can be assigned to multiple Azure resources, allowing a shared identity.',
  },
  {
    id: 'sec-012', topicId: 'managed-identity', difficulty: 'medium',
    question: 'A system-assigned managed identity has what lifecycle?',
    options: ['Independent of the resource', 'Created and deleted together with the single resource it belongs to', 'Permanent and cannot be deleted', 'Shared across a subscription'],
    correctAnswer: 1,
    explanation: 'A system-assigned identity is tied 1:1 to its resource and is automatically created and deleted with that resource.',
  },
  {
    id: 'sec-013', topicId: 'managed-identity', difficulty: 'hard',
    question: 'Which credential class in the Azure SDK automatically uses a managed identity when running in Azure?',
    options: ['ClientSecretCredential', 'DefaultAzureCredential', 'SharedKeyCredential', 'StorageSharedKeyCredential'],
    correctAnswer: 1,
    explanation: 'DefaultAzureCredential tries multiple sources in order, including managed identity when deployed in Azure, simplifying secretless auth.',
  },
  {
    id: 'sec-014', topicId: 'managed-identity', difficulty: 'medium',
    question: 'After enabling a managed identity, what must you still do for it to access a Key Vault secret?',
    options: ['Nothing', 'Grant the identity an appropriate role/policy (e.g., Key Vault Secrets User)', 'Store the vault key in code', 'Disable RBAC'],
    correctAnswer: 1,
    explanation: 'The identity must be authorized on the target resource — for example, assigned the Key Vault Secrets User role or an access policy.',
  },
  {
    id: 'sec-015', topicId: 'managed-identity', difficulty: 'hard',
    question: 'Internally, how does a managed identity obtain tokens on an Azure VM or App Service?',
    options: ['By reading a secret file', 'From the Azure Instance Metadata Service (IMDS) token endpoint', 'From the user', 'From a SAS URL'],
    correctAnswer: 1,
    explanation: 'The platform exposes a local IMDS endpoint that the SDK calls to obtain tokens for the managed identity, with no secrets involved.',
  },

  // ── Key Vault ───────────────────────────────────────────────────
  {
    id: 'sec-016', topicId: 'key-vault', difficulty: 'easy',
    question: 'Which of the following can Azure Key Vault store?',
    options: ['Only passwords', 'Secrets, keys, and certificates', 'Only TLS certificates', 'Container images'],
    correctAnswer: 1,
    explanation: 'Key Vault stores secrets (strings), cryptographic keys (for operations, optionally HSM-backed), and certificates.',
  },
  {
    id: 'sec-017', topicId: 'key-vault', difficulty: 'medium',
    question: 'Which Key Vault feature prevents permanent deletion of a vault/secret during a retention period?',
    options: ['Soft delete only', 'Purge protection', 'RBAC', 'Versioning'],
    correctAnswer: 1,
    explanation: 'Purge protection blocks hard-deletion (purge) until the soft-delete retention period elapses, protecting against malicious or accidental loss.',
  },
  {
    id: 'sec-018', topicId: 'key-vault', difficulty: 'medium',
    question: 'Which Key Vault tier provides HSM-backed keys?',
    options: ['Standard', 'Premium', 'Basic', 'Free'],
    correctAnswer: 1,
    explanation: 'The Premium tier offers HSM-backed keys; Standard uses software-protected keys.',
  },
  {
    id: 'sec-019', topicId: 'key-vault', difficulty: 'hard',
    question: 'You want an App Service app setting to pull its value directly from Key Vault at runtime. What do you use?',
    options: ['A SAS token in the value', 'A Key Vault reference in the app setting (@Microsoft.KeyVault(...))', 'Hard-code the secret', 'A connection string only'],
    correctAnswer: 1,
    explanation: 'Key Vault references let App Service/Functions resolve an app setting to a vault secret at runtime, using the app\'s managed identity.',
  },
  {
    id: 'sec-020', topicId: 'key-vault', difficulty: 'medium',
    question: 'For data-plane authorization, which is the recommended modern approach for Key Vault?',
    options: ['Vault access policies', 'Azure RBAC roles', 'Account keys', 'SAS tokens'],
    correctAnswer: 1,
    explanation: 'Azure RBAC is the recommended authorization model for Key Vault data plane, offering granular, manageable role assignments over legacy access policies.',
  },
  {
    id: 'sec-021', topicId: 'key-vault', difficulty: 'hard',
    question: 'How can you be notified to rotate a secret nearing expiration in Key Vault?',
    options: ['Poll constantly', 'Use Key Vault Event Grid notifications (e.g., SecretNearExpiry) to trigger automation', 'It cannot be automated', 'Store secrets in code'],
    correctAnswer: 1,
    explanation: 'Key Vault publishes events (SecretNearExpiry, SecretExpired) to Event Grid, which can trigger a Function/Logic App to rotate secrets.',
  },
  {
    id: 'sec-022', topicId: 'key-vault', difficulty: 'medium',
    question: 'Which SDK client reads a secret value from Key Vault?',
    options: ['KeyClient', 'SecretClient', 'CertificateClient', 'BlobClient'],
    correctAnswer: 1,
    explanation: 'SecretClient.GetSecretAsync reads secrets. KeyClient handles keys; CertificateClient handles certificates.',
  },

  // ── App Configuration ───────────────────────────────────────────
  {
    id: 'sec-023', topicId: 'app-configuration', difficulty: 'medium',
    question: 'Which service centrally stores non-secret application settings and feature flags?',
    options: ['Azure Key Vault', 'Azure App Configuration', 'Azure Storage', 'Azure Monitor'],
    correctAnswer: 1,
    explanation: 'Azure App Configuration centralizes app settings and feature flags; it can reference Key Vault for the secret values.',
  },
  {
    id: 'sec-024', topicId: 'app-configuration', difficulty: 'medium',
    question: 'In App Configuration, how do you keep separate values for dev and prod under the same key?',
    options: ['Use separate stores only', 'Use labels (e.g., dev/prod) on the key-value', 'Use SAS tokens', 'Use TTL'],
    correctAnswer: 1,
    explanation: 'Labels let you store environment-specific variants of the same key (e.g., key "Endpoint" with labels dev and prod).',
  },
  {
    id: 'sec-025', topicId: 'app-configuration', difficulty: 'hard',
    question: 'You want to progressively roll out a new feature to 10% of users without redeploying. What should you use?',
    options: ['A Key Vault secret', 'App Configuration feature flags / feature management', 'A new App Service plan', 'A SAS token'],
    correctAnswer: 1,
    explanation: 'Feature flags in App Configuration (with the feature management library) enable targeted/percentage rollouts and kill switches without redeploys.',
  },
  {
    id: 'sec-026', topicId: 'app-configuration', difficulty: 'medium',
    question: 'How should App Configuration handle the secret connection strings it needs to expose?',
    options: ['Store secrets in plain key-values', 'Store Key Vault references that point to secrets in Key Vault', 'Disable encryption', 'Embed them in code'],
    correctAnswer: 1,
    explanation: 'App Configuration should hold Key Vault references for secrets, keeping the actual secret values in Key Vault.',
  },

  // ── SAS ─────────────────────────────────────────────────────────
  {
    id: 'sec-027', topicId: 'sas', difficulty: 'medium',
    question: 'Which SAS type is signed with an Entra credential rather than the storage account key, making it the most secure?',
    options: ['Account SAS', 'Service SAS', 'User delegation SAS', 'Stored SAS'],
    correctAnswer: 2,
    explanation: 'A user delegation SAS is signed using Entra ID credentials (not the account key), is limited to Blob storage, and is more secure/revocable.',
  },
  {
    id: 'sec-028', topicId: 'sas', difficulty: 'medium',
    question: 'What does a stored access policy enable for a service SAS?',
    options: ['Faster downloads', 'Server-side control to revoke or modify the SAS after issuance', 'Encryption at rest', 'Cross-region replication'],
    correctAnswer: 1,
    explanation: 'A stored access policy lets you change or revoke a service SAS server-side without redistributing new tokens.',
  },
  {
    id: 'sec-029', topicId: 'sas', difficulty: 'hard',
    question: 'Which SAS grants access across multiple storage services (Blob, Queue, Table, File) using the account key?',
    options: ['Service SAS', 'User delegation SAS', 'Account SAS', 'Delegation policy'],
    correctAnswer: 2,
    explanation: 'An account SAS, signed with the account key, can grant access to multiple storage services and account-level operations.',
  },
  {
    id: 'sec-030', topicId: 'sas', difficulty: 'medium',
    question: 'Which of the following should you set to tightly scope a SAS token?',
    options: ['Only the account name', 'Permissions, start/expiry time, allowed IP ranges, and HTTPS-only', 'A managed identity', 'The blob content type'],
    correctAnswer: 1,
    explanation: 'A least-privilege SAS specifies permissions, a short validity window, allowed IPs, and HTTPS-only to minimize exposure.',
  },
  {
    id: 'sec-031', topicId: 'sas', difficulty: 'hard',
    question: 'A SAS token was leaked. For a user delegation SAS, how can you quickly invalidate it?',
    options: ['Wait for expiry only', 'Revoke the user delegation key (e.g., rotate the signing Entra key)', 'Delete the blob', 'Disable HTTPS'],
    correctAnswer: 1,
    explanation: 'Revoking the user delegation key invalidates all user delegation SAS tokens signed with it, providing fast revocation without rotating account keys.',
  },
  {
    id: 'sec-032', topicId: 'sas', difficulty: 'easy',
    question: 'What is the main advantage of a SAS over sharing the storage account key?',
    options: ['It is faster', 'It grants scoped, time-limited access without exposing the account key', 'It encrypts data', 'It enables versioning'],
    correctAnswer: 1,
    explanation: 'A SAS provides granular, time-bound, permission-scoped access so clients never receive the all-powerful account key.',
  },

  // ── Microsoft Graph ─────────────────────────────────────────────
  {
    id: 'sec-033', topicId: 'microsoft-graph', difficulty: 'easy',
    question: 'What is the single base endpoint for Microsoft Graph?',
    options: ['https://management.azure.com', 'https://graph.microsoft.com', 'https://login.microsoftonline.com', 'https://api.azure.com'],
    correctAnswer: 1,
    explanation: 'Microsoft Graph exposes Microsoft 365 and Entra data through the unified endpoint https://graph.microsoft.com.',
  },
  {
    id: 'sec-034', topicId: 'microsoft-graph', difficulty: 'medium',
    question: 'Which query parameter limits the properties returned by a Graph request for better performance?',
    options: ['$filter', '$select', '$expand', '$top'],
    correctAnswer: 1,
    explanation: '$select returns only the specified properties, reducing payload size and improving performance.',
  },
  {
    id: 'sec-035', topicId: 'microsoft-graph', difficulty: 'medium',
    question: 'A Graph call returns HTTP 429 with a Retry-After header. What should the app do?',
    options: ['Ignore it and retry immediately', 'Wait the indicated time, then retry (honor throttling)', 'Switch endpoints', 'Delete the token'],
    correctAnswer: 1,
    explanation: 'A 429 indicates throttling; the app should back off for the Retry-After duration before retrying.',
  },
  {
    id: 'sec-036', topicId: 'microsoft-graph', difficulty: 'hard',
    question: 'Which Graph capability reduces round-trips by combining multiple requests into one HTTP call?',
    options: ['$expand', 'JSON batching ($batch)', 'Delta query', 'Webhooks'],
    correctAnswer: 1,
    explanation: 'JSON batching via the $batch endpoint combines several requests into a single call, reducing latency and round-trips.',
  },
  {
    id: 'sec-037', topicId: 'microsoft-graph', difficulty: 'medium',
    question: 'An app needs to read all users in the directory with no signed-in user. Which permission type is required?',
    options: ['Delegated User.Read', 'Application User.Read.All (with admin consent)', 'A SAS token', 'No permission'],
    correctAnswer: 1,
    explanation: 'For app-only access to all users, the app needs an application permission like User.Read.All, which requires admin consent.',
  },

  // ── Mixed / scenario security ───────────────────────────────────
  {
    id: 'sec-038', topicId: 'managed-identity', difficulty: 'hard',
    scenario: 'A Function app must read secrets from Key Vault and write to a Storage account without any credentials in code.',
    question: 'What is the recommended approach?',
    options: ['Store keys in app settings', 'Enable a managed identity and grant it Key Vault Secrets User and Storage Blob Data Contributor roles', 'Use the storage account key', 'Use a SAS in code'],
    correctAnswer: 1,
    explanation: 'A managed identity with the appropriate RBAC roles enables secretless access to both Key Vault and Storage.',
  },
  {
    id: 'sec-039', topicId: 'identity-flows', difficulty: 'medium',
    question: 'Which endpoint provides the OpenID Connect configuration for token validation?',
    options: ['The /token endpoint', 'The /.well-known/openid-configuration discovery document', 'The Graph endpoint', 'The IMDS endpoint'],
    correctAnswer: 1,
    explanation: 'The well-known OpenID configuration document lists endpoints and signing keys (JWKS) needed to validate tokens.',
  },
  {
    id: 'sec-040', topicId: 'key-vault', difficulty: 'medium',
    question: 'Which operation would you use Key Vault keys (not secrets) for?',
    options: ['Storing a password string', 'Performing cryptographic operations like sign/verify and wrap/unwrap', 'Storing a connection string', 'Holding a feature flag'],
    correctAnswer: 1,
    explanation: 'Key Vault keys are used for cryptographic operations (encrypt/decrypt, sign/verify, wrap/unwrap), optionally HSM-backed; secrets store arbitrary values.',
  },
  {
    id: 'sec-041', topicId: 'sas', difficulty: 'medium',
    question: 'Which SAS is limited to a single storage service and is signed with the account key?',
    options: ['Account SAS', 'Service SAS', 'User delegation SAS', 'Token SAS'],
    correctAnswer: 1,
    explanation: 'A service SAS grants access to resources within one service (e.g., Blob) and is signed with the storage account key.',
  },
  {
    id: 'sec-042', topicId: 'managed-identity', difficulty: 'medium',
    question: 'Which RBAC concept grants a managed identity the ability to read blobs?',
    options: ['Storage Blob Data Reader role assignment', 'A SAS token', 'An access policy on the blob', 'The account key'],
    correctAnswer: 0,
    explanation: 'Assigning the Storage Blob Data Reader role to the identity grants data-plane read access to blobs via Entra ID.',
  },
  {
    id: 'sec-043', topicId: 'key-vault', difficulty: 'hard',
    question: 'A secret was accidentally deleted but soft delete is enabled. How do you recover it?',
    options: ['It is gone forever', 'Use the recover operation within the retention period', 'Restore from a SAS', 'Re-create the vault'],
    correctAnswer: 1,
    explanation: 'With soft delete, deleted secrets/keys/certs remain recoverable until the retention period ends; use the recover operation to restore them.',
  },
  {
    id: 'sec-044', topicId: 'identity-flows', difficulty: 'hard',
    question: 'Which token type does a confidential client use to obtain new access tokens without re-prompting the user?',
    options: ['ID token', 'Refresh token', 'SAS token', 'Bearer header'],
    correctAnswer: 1,
    explanation: 'A refresh token allows acquiring new access tokens (and ID tokens) silently after the access token expires, without user interaction.',
  },
  {
    id: 'sec-045', topicId: 'microsoft-graph', difficulty: 'medium',
    question: 'Which Graph feature lets you receive notifications when a resource (e.g., a mailbox) changes?',
    options: ['Delta query only', 'Change notifications (subscriptions/webhooks)', 'Batching', '$select'],
    correctAnswer: 1,
    explanation: 'Graph change notifications (subscriptions) push webhook callbacks when subscribed resources change, avoiding constant polling.',
  },
  {
    id: 'sec-046', topicId: 'identity-flows', difficulty: 'medium',
    question: 'What identifies the intended recipient (resource) of an access token?',
    options: ['The iss claim', 'The aud (audience) claim', 'The sub claim', 'The nonce'],
    correctAnswer: 1,
    explanation: 'The aud (audience) claim specifies the resource the token is intended for; APIs validate it during token validation.',
  },
  {
    id: 'sec-047', topicId: 'key-vault', difficulty: 'medium',
    question: 'A certificate stored in Key Vault should renew automatically before it expires. What can you configure?',
    options: ['Nothing; renewal is manual', 'An auto-rotation/issuance policy on the certificate', 'A SAS', 'Soft delete only'],
    correctAnswer: 1,
    explanation: 'Key Vault certificates support issuance/lifetime policies that auto-renew certificates with an integrated CA before expiry.',
  },
  {
    id: 'sec-048', topicId: 'managed-identity', difficulty: 'easy',
    question: 'Which is NOT a valid managed identity type?',
    options: ['System-assigned', 'User-assigned', 'Group-assigned', 'There are only system- and user-assigned'],
    correctAnswer: 2,
    explanation: 'Only system-assigned and user-assigned managed identities exist; "group-assigned" is not a managed identity type.',
  },
  {
    id: 'sec-049', topicId: 'sas', difficulty: 'medium',
    question: 'For a SAS, which permission letters typically represent read, write, delete, and list?',
    options: ['r, w, d, l', 'a, b, c, d', 'x, y, z, w', 'g, p, u, t'],
    correctAnswer: 0,
    explanation: 'SAS permissions use single letters such as r (read), w (write), d (delete), and l (list), combined to scope access.',
  },
  {
    id: 'sec-050', topicId: 'identity-flows', difficulty: 'hard',
    scenario: 'A multi-tenant SaaS app must let users from any organization sign in with their work accounts.',
    question: 'How should the app registration be configured?',
    options: ['Single tenant only', 'Multitenant (accounts in any organizational directory)', 'Personal accounts only', 'No sign-in'],
    correctAnswer: 1,
    explanation: 'Registering the app as multitenant allows users from any Entra ID organization to sign in; tenants consent on first use.',
  },
  {
    id: 'sec-051', topicId: 'key-vault', difficulty: 'medium',
    question: 'Which networking feature restricts Key Vault access to specific virtual networks?',
    options: ['SAS tokens', 'Key Vault firewall + private endpoints / VNet service endpoints', 'Soft delete', 'Feature flags'],
    correctAnswer: 1,
    explanation: 'The Key Vault firewall combined with private endpoints (or service endpoints) restricts data-plane access to selected networks.',
  },
  {
    id: 'sec-052', topicId: 'app-configuration', difficulty: 'medium',
    question: 'How can a client receive App Configuration updates without restarting?',
    options: ['It is impossible', 'Enable dynamic configuration refresh (polling/sentinel key)', 'Use a SAS', 'Redeploy each time'],
    correctAnswer: 1,
    explanation: 'The App Configuration provider supports dynamic refresh (often via a sentinel key) so apps pick up changes without restarting.',
  },
  {
    id: 'sec-053', topicId: 'identity-flows', difficulty: 'medium',
    question: 'Which Azure App Service feature adds authentication with minimal code, often called "Easy Auth"?',
    options: ['App Service Authentication/Authorization', 'Managed identity', 'CORS', 'Always On'],
    correctAnswer: 0,
    explanation: 'App Service Authentication ("Easy Auth") integrates identity providers (Entra ID, Google, etc.) without writing auth code.',
  },
  {
    id: 'sec-054', topicId: 'managed-identity', difficulty: 'hard',
    question: 'When multiple user-assigned identities are attached to a resource, what must the SDK specify to pick one?',
    options: ['Nothing; it auto-selects', 'The client ID (or resource ID) of the desired user-assigned identity', 'A SAS token', 'The account key'],
    correctAnswer: 1,
    explanation: 'With multiple user-assigned identities, you must specify the target identity\'s client ID (or resource ID) so the runtime requests the correct token.',
  },
  {
    id: 'sec-055', topicId: 'key-vault', difficulty: 'medium',
    question: 'What is the recommended way for code to read a Key Vault secret in production?',
    options: ['Hard-code the secret', 'Use SecretClient with DefaultAzureCredential (managed identity)', 'Embed the vault key', 'Use a public URL'],
    correctAnswer: 1,
    explanation: 'Use the SecretClient with DefaultAzureCredential so the app authenticates via its managed identity — no secrets in code.',
  },
  {
    id: 'sec-056', topicId: 'microsoft-graph', difficulty: 'medium',
    question: 'Which query parameter would you use to retrieve only the first 10 results from a Graph collection?',
    options: ['$select', '$top=10', '$expand', '$filter'],
    correctAnswer: 1,
    explanation: '$top limits the number of items returned (e.g., $top=10), with @odata.nextLink for paging.',
  },
  {
    id: 'sec-057', topicId: 'identity-flows', difficulty: 'medium',
    question: 'What is the purpose of the scope parameter in a token request?',
    options: ['To set the token lifetime', 'To request specific permissions/resources for the access token', 'To choose a region', 'To enable HTTPS'],
    correctAnswer: 1,
    explanation: 'Scopes specify which permissions/resources the requested access token should grant (e.g., https://graph.microsoft.com/User.Read).',
  },
  {
    id: 'sec-058', topicId: 'sas', difficulty: 'hard',
    scenario: 'A mobile app must upload images to a specific blob container for 15 minutes without embedding any storage credentials.',
    question: 'What should the backend issue to the app?',
    options: ['The storage account key', 'A short-lived user delegation SAS scoped to the container with write permission', 'A managed identity', 'A Key Vault secret'],
    correctAnswer: 1,
    explanation: 'A short-lived, write-scoped user delegation SAS lets the mobile app upload without exposing account keys, and it auto-expires.',
  },
  {
    id: 'sec-059', topicId: 'key-vault', difficulty: 'easy',
    question: 'Which statement about Key Vault soft delete is correct in current Azure defaults?',
    options: ['It must be manually enabled', 'It is enabled by default and cannot be disabled', 'It deletes data immediately', 'It only applies to certificates'],
    correctAnswer: 1,
    explanation: 'Soft delete is enabled by default on Key Vaults and cannot be turned off, ensuring deleted objects are recoverable during retention.',
  },
  {
    id: 'sec-060', topicId: 'identity-flows', difficulty: 'hard',
    question: 'Which flow should a confidential web app use to sign in users and call APIs on their behalf?',
    options: ['Client Credentials', 'Authorization Code flow', 'Device Code', 'Implicit'],
    correctAnswer: 1,
    explanation: 'A confidential web app uses the Authorization Code flow to authenticate the user and obtain tokens (and refresh tokens) to call APIs as the user.',
  },
]

export const securityQuestions = buildQuestions('implement-security', 'Implement Azure security', seeds)
