import { buildQuestions, QSeed } from './_builder'

const seeds: QSeed[] = [
  // ── Cosmos DB: partitioning & throughput ────────────────────────
  {
    id: 'sto-001', topicId: 'cosmos-partitioning', difficulty: 'medium',
    question: 'What characterizes a GOOD partition key in Azure Cosmos DB?',
    options: ['Low cardinality so values repeat often', 'High cardinality with even distribution of storage and requests', 'Always the document id', 'A timestamp for recent writes'],
    correctAnswer: 1,
    explanation: 'A good partition key has high cardinality and spreads both storage and request volume evenly to avoid hot partitions and throttling.',
  },
  {
    id: 'sto-002', topicId: 'cosmos-partitioning', difficulty: 'easy',
    question: 'What is the maximum size of a single logical partition in Cosmos DB?',
    options: ['10 GB', '20 GB', '50 GB', 'Unlimited'],
    correctAnswer: 1,
    explanation: 'A single logical partition (all items sharing a partition key value) is limited to 20 GB of storage.',
  },
  {
    id: 'sto-003', topicId: 'cosmos-partitioning', difficulty: 'medium',
    question: 'A Cosmos DB request returns HTTP 429. What does this indicate?',
    options: ['Authentication failed', 'The request rate exceeded provisioned throughput (RU/s)', 'The item was not found', 'The partition key is missing'],
    correctAnswer: 1,
    explanation: 'HTTP 429 "Request rate too large" means RU/s consumption exceeded the provisioned/available throughput. Increase RU/s or implement retry with backoff.',
  },
  {
    id: 'sto-004', topicId: 'cosmos-partitioning', difficulty: 'hard',
    question: 'Which throughput mode is best for a workload with unpredictable, spiky traffic and long idle periods?',
    options: ['Manual provisioned throughput', 'Autoscale or serverless', 'Reserved capacity only', 'No throughput needed'],
    correctAnswer: 1,
    explanation: 'Autoscale adjusts RU/s automatically to the workload; serverless bills per request — both suit spiky/intermittent traffic better than fixed manual RU/s.',
  },
  {
    id: 'sto-005', topicId: 'cosmos-partitioning', difficulty: 'medium',
    question: 'How can you reduce the RU cost of a Cosmos DB query?',
    options: ['Query without the partition key', 'Include the partition key to avoid cross-partition fan-out', 'Use SELECT * always', 'Disable indexing entirely'],
    correctAnswer: 1,
    explanation: 'Including the partition key scopes the query to one physical partition, avoiding costly cross-partition fan-out and lowering RU charges.',
  },

  // ── Cosmos DB: consistency ──────────────────────────────────────
  {
    id: 'sto-006', topicId: 'cosmos-consistency', difficulty: 'easy',
    question: 'What is the default consistency level in Azure Cosmos DB?',
    options: ['Strong', 'Bounded Staleness', 'Session', 'Eventual'],
    correctAnswer: 2,
    explanation: 'Session is the default consistency level; it guarantees read-your-own-writes within a client session and balances consistency with performance.',
  },
  {
    id: 'sto-007', topicId: 'cosmos-consistency', difficulty: 'medium',
    question: 'Which Cosmos DB consistency level offers the strongest guarantee but the highest latency and cost?',
    options: ['Eventual', 'Consistent Prefix', 'Session', 'Strong'],
    correctAnswer: 3,
    explanation: 'Strong consistency guarantees linearizable reads (always the latest committed write) at the cost of higher latency and reduced availability for multi-region writes.',
  },
  {
    id: 'sto-008', topicId: 'cosmos-consistency', difficulty: 'hard',
    question: 'Order the Cosmos DB consistency levels from strongest to weakest.',
    options: ['Strong, Session, Bounded Staleness, Eventual, Consistent Prefix', 'Strong, Bounded Staleness, Session, Consistent Prefix, Eventual', 'Eventual, Session, Strong, Bounded Staleness, Consistent Prefix', 'Bounded Staleness, Strong, Session, Eventual, Consistent Prefix'],
    correctAnswer: 1,
    explanation: 'The order is Strong > Bounded Staleness > Session > Consistent Prefix > Eventual.',
  },
  {
    id: 'sto-009', topicId: 'cosmos-consistency', difficulty: 'medium',
    question: 'Which consistency level bounds how far reads can lag behind writes by a number of versions or a time interval?',
    options: ['Session', 'Bounded Staleness', 'Eventual', 'Consistent Prefix'],
    correctAnswer: 1,
    explanation: 'Bounded Staleness guarantees reads lag writes by at most K versions or T time, configurable on the account.',
  },
  {
    id: 'sto-010', topicId: 'cosmos-consistency', difficulty: 'hard',
    question: 'On a per-request basis, you can change the consistency level relative to the account default how?',
    options: ['Strengthen it above the default', 'Only relax it to a weaker level than the account default', 'Set any level freely', 'It cannot be changed per request'],
    correctAnswer: 1,
    explanation: 'Per request you may relax consistency to a weaker level than the account default, but you cannot strengthen beyond the configured account level.',
  },
  {
    id: 'sto-011', topicId: 'cosmos-consistency', difficulty: 'medium',
    question: 'Which consistency level guarantees you never see writes out of order, though reads may lag?',
    options: ['Eventual', 'Consistent Prefix', 'Strong', 'Session'],
    correctAnswer: 1,
    explanation: 'Consistent Prefix guarantees reads never see out-of-order writes (no gaps), but they may be behind the latest write.',
  },

  // ── Cosmos DB: change feed ──────────────────────────────────────
  {
    id: 'sto-012', topicId: 'cosmos-changefeed', difficulty: 'medium',
    question: 'Which operations does the Cosmos DB change feed capture?',
    options: ['Inserts and updates only', 'Inserts, updates, and deletes', 'Deletes only', 'Reads'],
    correctAnswer: 0,
    explanation: 'The change feed records creates and updates in modification order. It does not capture deletes — use a soft-delete flag with TTL if delete tracking is needed.',
  },
  {
    id: 'sto-013', topicId: 'cosmos-changefeed', difficulty: 'hard',
    question: 'What does the Change Feed Processor use to track its progress and coordinate multiple consumers?',
    options: ['A queue', 'A lease container', 'A blob lock', 'A Redis key'],
    correctAnswer: 1,
    explanation: 'The Change Feed Processor stores its position and partition leases in a lease container, enabling fault tolerance and parallel consumers.',
  },
  {
    id: 'sto-014', topicId: 'cosmos-changefeed', difficulty: 'medium',
    question: 'What is the easiest way to process Cosmos DB change feed events with minimal code?',
    options: ['Poll the REST API on a timer', 'Use an Azure Functions Cosmos DB trigger', 'Read from a Service Bus queue', 'Use a stored procedure'],
    correctAnswer: 1,
    explanation: 'The Azure Functions Cosmos DB trigger is built on the change feed and invokes your function automatically for changed items.',
  },
  {
    id: 'sto-015', topicId: 'cosmos-changefeed', difficulty: 'medium',
    question: 'You need to track deletions for an event-sourcing scenario in Cosmos DB. What approach works with the change feed?',
    options: ['The change feed captures deletes directly', 'Use soft delete (a deleted flag) plus TTL, then react to the update', 'Use a database trigger', 'It is impossible'],
    correctAnswer: 1,
    explanation: 'Because the change feed ignores hard deletes, mark items with a soft-delete flag (an update, which IS captured) and optionally set TTL for cleanup.',
  },

  // ── Cosmos DB: SDK & APIs ───────────────────────────────────────
  {
    id: 'sto-016', topicId: 'cosmos-partitioning', difficulty: 'medium',
    question: 'In the Cosmos DB .NET SDK, which method efficiently reads a single item when you know its id and partition key?',
    options: ['GetItemQueryIterator', 'ReadItemAsync(id, partitionKey)', 'CreateItemAsync', 'ReadContainerAsync'],
    correctAnswer: 1,
    explanation: 'ReadItemAsync with the id and partition key is a point read — the cheapest and fastest way to retrieve a single document (around 1 RU for a 1KB item).',
  },
  {
    id: 'sto-017', topicId: 'cosmos-partitioning', difficulty: 'easy',
    question: 'Which Cosmos DB API stores data as JSON documents and uses SQL-like queries?',
    options: ['Cassandra API', 'MongoDB API', 'Core (NoSQL/SQL) API', 'Gremlin API'],
    correctAnswer: 2,
    explanation: 'The Core (NoSQL) API stores JSON documents and supports SQL-like query syntax. It is the recommended default API.',
  },
  {
    id: 'sto-018', topicId: 'cosmos-partitioning', difficulty: 'hard',
    question: 'A point read of a 1 KB item in Cosmos DB typically costs approximately how many RUs?',
    options: ['About 1 RU', 'About 100 RUs', 'About 1000 RUs', 'Zero RUs'],
    correctAnswer: 0,
    explanation: 'A point read (by id + partition key) of a 1 KB item costs roughly 1 RU, much cheaper than an equivalent query.',
  },
  {
    id: 'sto-019', topicId: 'cosmos-partitioning', difficulty: 'medium',
    question: 'Which server-side construct in Cosmos DB executes within a single logical partition and is atomic?',
    options: ['User-defined function (UDF)', 'Stored procedure', 'Cross-partition query', 'Change feed'],
    correctAnswer: 1,
    explanation: 'Stored procedures run transactionally (atomically) but are scoped to a single logical partition key value.',
  },
  {
    id: 'sto-020', topicId: 'cosmos-partitioning', difficulty: 'medium',
    question: 'To automatically delete items after a period, what Cosmos DB feature do you configure?',
    options: ['Change feed', 'Time to Live (TTL)', 'Indexing policy', 'Consistency level'],
    correctAnswer: 1,
    explanation: 'TTL automatically expires and removes items after the configured number of seconds, set at container or item level.',
  },

  // ── Blob: tiers ─────────────────────────────────────────────────
  {
    id: 'sto-021', topicId: 'blob-tiers', difficulty: 'easy',
    question: 'Which blob access tier offers the lowest storage cost but requires rehydration before data can be read?',
    options: ['Hot', 'Cool', 'Cold', 'Archive'],
    correctAnswer: 3,
    explanation: 'Archive is the cheapest for storage but is offline; blobs must be rehydrated (to Hot/Cool) before they can be read, which can take hours.',
  },
  {
    id: 'sto-022', topicId: 'blob-tiers', difficulty: 'medium',
    question: 'Data accessed roughly once a month and stored for at least 30 days fits which tier best?',
    options: ['Hot', 'Cool', 'Archive', 'Premium'],
    correctAnswer: 1,
    explanation: 'The Cool tier targets infrequently accessed data stored for at least 30 days, with lower storage and higher access costs than Hot.',
  },
  {
    id: 'sto-023', topicId: 'blob-tiers', difficulty: 'medium',
    question: 'Which statement about the Hot tier is correct?',
    options: ['Lowest storage cost', 'Highest storage cost, lowest access cost', 'Offline storage', 'Minimum 180-day retention'],
    correctAnswer: 1,
    explanation: 'Hot has the highest storage cost but the lowest access/transaction costs, ideal for frequently accessed data.',
  },
  {
    id: 'sto-024', topicId: 'blob-tiers', difficulty: 'hard',
    question: 'You set a blob to Archive and now need to read it quickly. What must happen first?',
    options: ['Nothing; archive blobs are readable directly', 'Rehydrate it by changing the tier to Hot or Cool (optionally High priority)', 'Delete and re-upload it', 'Enable versioning'],
    correctAnswer: 1,
    explanation: 'Archive blobs are offline. You must rehydrate by setting the tier to Hot/Cool; High priority rehydration is faster but costs more.',
  },
  {
    id: 'sto-025', topicId: 'blob-tiers', difficulty: 'medium',
    question: 'Which tiers can be set at the individual blob level versus only at the account level?',
    options: ['Archive can only be set at the account level', 'Hot, Cool, Cold, and Archive can be set at the blob level (Archive is blob-only)', 'Only Hot can be set per blob', 'None can be set per blob'],
    correctAnswer: 1,
    explanation: 'Hot/Cool/Cold can be set at account or blob level; Archive is set at the blob level only.',
  },

  // ── Blob: lifecycle ─────────────────────────────────────────────
  {
    id: 'sto-026', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'Lifecycle management policies in Blob Storage are defined using what format?',
    options: ['XML rules', 'JSON rules with conditions and actions', 'YAML manifests', 'CSV files'],
    correctAnswer: 1,
    explanation: 'Lifecycle management policies are JSON documents with rule filters and actions (e.g., tierToCool, delete) based on blob age.',
  },
  {
    id: 'sto-027', topicId: 'blob-lifecycle', difficulty: 'hard',
    question: 'Which lifecycle condition moves blobs to Archive 90 days after last modification?',
    options: ['tierToArchive with daysAfterModificationGreaterThan: 90', 'delete after 90 days', 'tierToCool immediately', 'enableAutoTiering: true'],
    correctAnswer: 0,
    explanation: 'A lifecycle rule action tierToArchive with daysAfterModificationGreaterThan set to 90 archives blobs 90 days after they were last modified.',
  },
  {
    id: 'sto-028', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'Which actions can a blob lifecycle policy perform?',
    options: ['Only delete blobs', 'Tier blobs down (Cool/Cold/Archive) and delete them', 'Encrypt blobs', 'Replicate blobs to another region'],
    correctAnswer: 1,
    explanation: 'Lifecycle actions include tierToCool, tierToCold, tierToArchive, and delete, based on age conditions.',
  },

  // ── Blob: properties, metadata, SDK ─────────────────────────────
  {
    id: 'sto-029', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'What is the difference between blob properties and blob metadata?',
    options: ['They are the same', 'Properties are system-defined (e.g., Content-Type); metadata are custom user-defined name/value pairs', 'Metadata is system-defined; properties are custom', 'Both are read-only'],
    correctAnswer: 1,
    explanation: 'Properties are system-defined values like Content-Type and ETag; metadata are arbitrary user-defined name/value pairs (x-ms-meta-*).',
  },
  {
    id: 'sto-030', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'In the Azure Storage v12 .NET SDK, which client type represents a single blob?',
    options: ['BlobServiceClient', 'BlobContainerClient', 'BlobClient', 'QueueClient'],
    correctAnswer: 2,
    explanation: 'BlobClient operates on a single blob; BlobContainerClient manages a container; BlobServiceClient manages the account-level service.',
  },
  {
    id: 'sto-031', topicId: 'blob-lifecycle', difficulty: 'hard',
    question: 'You upload a blob and need to ensure it is not overwritten if it already exists. Which approach works?',
    options: ['Always pass overwrite: true', 'Use an If-None-Match: * conditional (or overwrite: false)', 'Disable versioning', 'Use the Archive tier'],
    correctAnswer: 1,
    explanation: 'Using a conditional header like If-None-Match: * (or overwrite: false in the SDK) prevents overwriting an existing blob, returning a 409 if it exists.',
  },
  {
    id: 'sto-032', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'Which feature lets you serve a static website (HTML/CSS/JS) directly from a storage account?',
    options: ['The $web container with static website hosting enabled', 'A blob trigger', 'Table storage', 'A queue'],
    correctAnswer: 0,
    explanation: 'Enabling static website hosting serves content from the special $web container with configurable index and error documents.',
  },
  {
    id: 'sto-033', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'Which features protect blob data from accidental deletion or modification?',
    options: ['Soft delete, versioning, and immutability (WORM)', 'Only encryption', 'Only RBAC', 'Lifecycle policies only'],
    correctAnswer: 0,
    explanation: 'Soft delete (recover deleted blobs), versioning (keep previous versions), and immutability policies (WORM) protect against data loss/tampering.',
  },
  {
    id: 'sto-034', topicId: 'blob-lifecycle', difficulty: 'hard',
    question: 'For large blob uploads, which approach improves throughput and resilience?',
    options: ['Single PUT for the whole file', 'Upload in blocks (Put Block / Put Block List) in parallel', 'Use the Archive tier', 'Disable retries'],
    correctAnswer: 1,
    explanation: 'Block blobs are uploaded as parallel blocks then committed with Put Block List, improving throughput and allowing resume on failure.',
  },
  {
    id: 'sto-035', topicId: 'blob-tiers', difficulty: 'medium',
    question: 'Which redundancy option keeps copies in two regions to protect against a regional outage?',
    options: ['LRS', 'ZRS', 'GRS (Geo-redundant storage)', 'None'],
    correctAnswer: 2,
    explanation: 'GRS replicates data to a secondary region. LRS is single-datacenter; ZRS spans availability zones in one region.',
  },
  {
    id: 'sto-036', topicId: 'blob-tiers', difficulty: 'easy',
    question: 'Which storage redundancy spreads copies across availability zones within a single region?',
    options: ['LRS', 'ZRS', 'GRS', 'RA-GRS'],
    correctAnswer: 1,
    explanation: 'ZRS (Zone-redundant storage) replicates synchronously across availability zones in the primary region.',
  },
  {
    id: 'sto-037', topicId: 'blob-tiers', difficulty: 'hard',
    question: 'You need read access to your data in the secondary region during a primary outage. Which redundancy option provides this?',
    options: ['LRS', 'ZRS', 'RA-GRS (read-access geo-redundant)', 'GRS without read access'],
    correctAnswer: 2,
    explanation: 'RA-GRS adds read access to the secondary region endpoint, so applications can read replicated data during a primary region failure.',
  },
  {
    id: 'sto-038', topicId: 'cosmos-partitioning', difficulty: 'medium',
    question: 'What is a synthetic partition key in Cosmos DB?',
    options: ['A key generated by combining multiple properties to increase cardinality', 'The system _rid value', 'A random GUID always', 'The container name'],
    correctAnswer: 0,
    explanation: 'A synthetic partition key concatenates two or more properties (or adds a suffix) to achieve higher cardinality and better distribution.',
  },
  {
    id: 'sto-039', topicId: 'cosmos-consistency', difficulty: 'medium',
    question: 'Which consistency level is most appropriate for a user reading their own recently submitted profile change in a single-region app?',
    options: ['Eventual', 'Session', 'Consistent Prefix', 'None'],
    correctAnswer: 1,
    explanation: 'Session consistency provides read-your-own-writes within the same client session, ideal for a user seeing their own updates.',
  },
  {
    id: 'sto-040', topicId: 'cosmos-changefeed', difficulty: 'medium',
    question: 'The change feed guarantees ordering at what scope?',
    options: ['Across the entire container globally', 'Within each logical partition', 'Across all databases', 'No ordering at all'],
    correctAnswer: 1,
    explanation: 'Change feed entries are ordered by modification time within each partition; there is no global cross-partition ordering guarantee.',
  },
  {
    id: 'sto-041', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'How is blob metadata retrieved relative to blob content?',
    options: ['You must download the whole blob', 'Metadata is returned with Get Blob Properties without downloading content', 'Metadata cannot be read', 'Only via lifecycle policies'],
    correctAnswer: 1,
    explanation: 'Get Blob Properties returns system properties and user metadata without downloading the blob body.',
  },
  {
    id: 'sto-042', topicId: 'blob-tiers', difficulty: 'easy',
    question: 'Which storage account redundancy is the cheapest but only protects against single-machine failures in one datacenter?',
    options: ['LRS (Locally redundant storage)', 'GRS', 'RA-GRS', 'ZRS'],
    correctAnswer: 0,
    explanation: 'LRS keeps three copies within a single datacenter — the lowest cost but no protection against datacenter or regional outages.',
  },
  {
    id: 'sto-043', topicId: 'cosmos-partitioning', difficulty: 'hard',
    question: 'Cross-partition queries can be made more efficient by enabling what on the query options?',
    options: ['Disabling indexing', 'Setting MaxConcurrency/MaxItemCount appropriately for parallelism', 'Using Strong consistency', 'Lowering RU/s'],
    correctAnswer: 1,
    explanation: 'Tuning MaxConcurrency (degree of parallelism) and MaxItemCount controls how cross-partition queries fan out and page, improving performance.',
  },
  {
    id: 'sto-044', topicId: 'cosmos-partitioning', difficulty: 'medium',
    question: 'Which indexing behavior is the default in a Cosmos DB container?',
    options: ['No properties are indexed', 'All properties are automatically indexed', 'Only the id is indexed', 'Only the partition key is indexed'],
    correctAnswer: 1,
    explanation: 'By default Cosmos DB automatically indexes all properties. You can customize the indexing policy to include/exclude paths to optimize cost.',
  },
  {
    id: 'sto-045', topicId: 'cosmos-consistency', difficulty: 'hard',
    question: 'Which consistency level provides the lowest latency and highest availability but no ordering guarantees?',
    options: ['Strong', 'Bounded Staleness', 'Session', 'Eventual'],
    correctAnswer: 3,
    explanation: 'Eventual consistency offers the best performance and availability with no ordering or recency guarantee — replicas converge over time.',
  },
  {
    id: 'sto-046', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'A blob lifecycle rule filter can target a subset of blobs based on what?',
    options: ['Only the entire account', 'Blob prefix (path) and blob index tags', 'Only container name', 'Only file extension'],
    correctAnswer: 1,
    explanation: 'Lifecycle rule filters can scope by blob name prefix and by blob index tags, plus blob type, to target specific blobs.',
  },
  {
    id: 'sto-047', topicId: 'blob-tiers', difficulty: 'medium',
    question: 'Which minimum retention period applies before deleting a Cool-tier blob avoids an early deletion charge?',
    options: ['30 days', '90 days', '180 days', 'No minimum'],
    correctAnswer: 0,
    explanation: 'Cool tier has a 30-day minimum; deleting or tiering-out earlier incurs an early deletion fee. Cold is 90 days, Archive 180 days.',
  },
  {
    id: 'sto-048', topicId: 'cosmos-changefeed', difficulty: 'medium',
    question: 'Which scenario is NOT a typical use of the Cosmos DB change feed?',
    options: ['Real-time materialized views', 'Replicating data to another store', 'Triggering downstream processing', 'Enforcing strong consistency on reads'],
    correctAnswer: 3,
    explanation: 'Change feed enables event-driven processing, replication, and materialized views. Consistency level is a separate account/request setting, not a change feed function.',
  },
  {
    id: 'sto-049', topicId: 'cosmos-partitioning', difficulty: 'medium',
    question: 'To bulk-import many items efficiently with the Cosmos DB SDK, what should you enable?',
    options: ['Strong consistency', 'Bulk execution (AllowBulkExecution)', 'Cross-partition queries', 'Manual retries only'],
    correctAnswer: 1,
    explanation: 'Setting AllowBulkExecution = true in the CosmosClientOptions optimizes high-volume writes by batching operations per partition.',
  },
  {
    id: 'sto-050', topicId: 'blob-lifecycle', difficulty: 'hard',
    question: 'You need an append-only log file in Blob Storage. Which blob type is designed for efficient append operations?',
    options: ['Block blob', 'Append blob', 'Page blob', 'Archive blob'],
    correctAnswer: 1,
    explanation: 'Append blobs are optimized for append operations (e.g., logging). Block blobs suit general files; page blobs back VHDs/random access.',
  },
  {
    id: 'sto-051', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'Which blob type underpins Azure managed disks and supports random read/write to 512-byte pages?',
    options: ['Block blob', 'Append blob', 'Page blob', 'Static blob'],
    correctAnswer: 2,
    explanation: 'Page blobs support random access in 512-byte pages and back Azure VM disks (VHDs).',
  },
  {
    id: 'sto-052', topicId: 'cosmos-consistency', difficulty: 'medium',
    question: 'Increasing consistency strength in a multi-region Cosmos DB account generally has what trade-off?',
    options: ['Lower latency and higher availability', 'Higher latency, higher RU cost, and reduced availability', 'No trade-offs', 'Cheaper storage'],
    correctAnswer: 1,
    explanation: 'Stronger consistency increases read latency and RU cost and can reduce availability (especially for multi-region writes).',
  },
  {
    id: 'sto-053', topicId: 'cosmos-partitioning', difficulty: 'hard',
    scenario: 'An IoT solution writes telemetry from millions of devices to Cosmos DB and queries are usually scoped to a single device.',
    question: 'What is the best partition key choice?',
    options: ['A constant value', 'deviceId', 'The current timestamp', 'A random number per write'],
    correctAnswer: 1,
    explanation: 'deviceId gives high cardinality and matches the query pattern (per-device), distributing load while keeping queries single-partition.',
  },
  {
    id: 'sto-054', topicId: 'blob-tiers', difficulty: 'easy',
    question: 'Which service-side feature encrypts all blob data at rest by default?',
    options: ['You must enable it manually', 'Storage Service Encryption (SSE) is on by default', 'Only Premium accounts encrypt data', 'Encryption requires a SAS'],
    correctAnswer: 1,
    explanation: 'Azure Storage encrypts data at rest by default using Storage Service Encryption (with Microsoft-managed or customer-managed keys).',
  },
  {
    id: 'sto-055', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'Which header do you set to control how browsers cache a blob served over HTTP?',
    options: ['Content-Encoding', 'Cache-Control', 'x-ms-meta-cache', 'ETag'],
    correctAnswer: 1,
    explanation: 'The Cache-Control blob property instructs browsers/CDNs how long to cache the blob.',
  },
  {
    id: 'sto-056', topicId: 'cosmos-changefeed', difficulty: 'hard',
    question: 'You want two independent downstream systems to each process every change from a Cosmos container. How do you isolate their progress?',
    options: ['Share one lease container', 'Use separate lease containers (or lease prefixes) per consumer', 'Disable the change feed', 'Use Strong consistency'],
    correctAnswer: 1,
    explanation: 'Each independent consumer should use its own lease container (or a distinct lease prefix) so their checkpoints/progress do not interfere.',
  },
  {
    id: 'sto-057', topicId: 'cosmos-partitioning', difficulty: 'medium',
    question: 'What is the consequence of choosing a low-cardinality partition key like "country" for a global app concentrated in one country?',
    options: ['Perfectly even distribution', 'A hot partition that throttles and limits scale', 'Lower RU cost', 'Stronger consistency'],
    correctAnswer: 1,
    explanation: 'Low cardinality concentrated in one value creates a hot partition that hits the 20 GB/throughput limits and causes throttling.',
  },
  {
    id: 'sto-058', topicId: 'blob-tiers', difficulty: 'medium',
    question: 'Which combination minimizes cost for data that is written once and rarely read but must be retained for years for compliance?',
    options: ['Hot tier with versioning', 'Archive tier with an immutability (WORM) policy', 'Cool tier with soft delete only', 'Premium block blob'],
    correctAnswer: 1,
    explanation: 'Archive minimizes storage cost for rarely accessed long-term data, and an immutability/WORM policy enforces compliance retention.',
  },
  {
    id: 'sto-059', topicId: 'blob-lifecycle', difficulty: 'medium',
    question: 'Which SDK client would you use to enumerate all blobs in a container?',
    options: ['BlobServiceClient.GetBlobContainers', 'BlobContainerClient.GetBlobs / GetBlobsAsync', 'BlobClient.Download', 'QueueClient.ReceiveMessages'],
    correctAnswer: 1,
    explanation: 'BlobContainerClient.GetBlobs (or GetBlobsAsync) lists blobs in a container, supporting prefixes and paging.',
  },
  {
    id: 'sto-060', topicId: 'cosmos-consistency', difficulty: 'hard',
    scenario: 'A financial ledger must never return stale balances and runs in a single write region.',
    question: 'Which consistency level should you configure?',
    options: ['Eventual', 'Session', 'Strong', 'Consistent Prefix'],
    correctAnswer: 2,
    explanation: 'Strong consistency guarantees reads always reflect the latest committed write — appropriate for a ledger requiring no stale reads.',
  },
]

export const storageQuestions = buildQuestions('develop-storage', 'Develop for Azure storage', seeds)
